### ISSUE TITLE
Server errato in SerieHD

### ISSUE THREAD

**Issue by axlt2002** [streamondemand/plugin.video.streamondemand#102]
Ciao,

Riporto qui per maggiore visibilità quanto ho segnalato sul forum sperando di esservi di aiuto in qualche modo.

Utilizzando SOD, se si cerca di guardare su SerieHD, ad esempio, l'episodio 10 della stagione 6 di American Horror History, vengono mostrate le tre seguenti opzioni: openload @360p, openlaod @1080p e videomega @1080p. Con openload (grazie all'ultimo aggiornamento) non ci sono problemi, mentre se provo a vedere l'episodio tramite videomega, compare il pop-up "Processo terminato" ed il video non parte.

La cosa strana è che se vado direttamente sul sito SerieHD, per la versione 1080p, le due opzioni sono openload e rapidvideo. Entrambi (una volta chiuse le 1220293 finestre di pubblicità!) vengono riprodotti.

Sembra quindi che SOD "confonda" il server nel momento in cui legge dalla pagina di SerieHD, riconoscendolo come videomega anzichè come rapidvideo.

Risulta anche a voi?

**Comment by costaplus** [comment]
Ciao,
Purtroppo SoD lavora sullo scraping, quindi l'errore da te riscontrato può essere che il link al video come tu.mi confermi è offuscato da miriade di pop pup vari o in alcuni casi fanno riferimento a link non più validi!
Succede, ma quello non dipende da noi, il fatto è che se cambiano spesso la semantica della pagina dovremmo avere anche il tempo utile per sistemarlo e ti assicurano che cambiano dal giorno alla notte su molti canali per poi non parlare dei cambi host.
Quindi questo per dirti è complicato gestire il singolo errore, diverso è se si verifica su tutto il canale allora lì possiamo daro un'occhio.
Mi spiace.
Ciao e grazie per la segnalazione.

**Comment by peppesr** [comment]
Ciao, aggiungo qui perché si parla di Serie HD, da ieri forse a causa di cambio del dominio non è più disponibile nessun contenuto. sul sito .me i contenuti sono presenti http://www.seriehd.me/ qui in kodi da serie TV https://puu.sh/ugzMj/c016e08688.jpg a nessun contenuto disponibile https://puu.sh/ugzLG/ee63f70be2.jpg
grazie
Peppe

**Comment by Dr-Zer0** [comment]
Entrambi i problemi segnalati sono stati risolti.
