### ISSUE TITLE
New channel

### ISSUE THREAD

**Issue by dentaku65** [streamondemand/plugin.video.streamondemand#123]
@Dr-Zer0 @costaplus @MrTruth0 

Potete darmi una mano con questo quando avete un po' di tempo?

http://pastebin.com/tY373EHD

**Comment by MrTruth0** [comment]
Mi dispiace, ma non sono riuscito a risolvere nulla ... mostra sempre che è richiesto javascript, magari DrZero o Costa riescono a risolvere

**Comment by costaplus** [comment]
i Cookie normalmente vengono impostati dall'host, può essere che abbiano settato un cookie specifico deniminato ..... cmq una cosa un pò strana, ma se funziona....

**Comment by Scruffy3000** [comment]
Non ho ben capito a che punto siate arrivati, ad ogni modo:
- la prima pagina ti da una specie di "challenge" javascript, che fa una decrittazione AES con crittotesto, chiave e iv sempre all'interno del javascript, poi setta il risultato come cookie e ti ridireziona 
- il tutto si può parsare e rifare in python (ma bisogna accettare qualche dipendenza per l'AES), se volete un esempio piuttosto brutto, con pyCrypto: http://pastebin.com/xVvZU4E9
- il problema seguente è mettere il cookie nella jar di sistema e qui non ho idea di come fare, visto che di solito credo lavori da file, ma qualche modo dovrebbe esserci.

**Comment by Scruffy3000** [comment]
Se qualcuno vuole dare un'occhiata / lavorarci sopra, qua c'è una prima bozza (è da ripulire, commentata molto poco e ha qualche problema) che sembra funzionare: http://pastebin.com/HAtfEcF0

Di base usa lo stesso codice del commento sopra, ma, in più, salva i cookie su disco nella posizione in cui il plugin se li aspetta (almeno da quel che ha capito da una scorsa veloce al codice); la parte di estrazione dei cookie viene chiamata quando la prima richiesta su un "punto di ingresso" (peliculas, categorie, peliculas_src) restituisce la pagina col challenge javascript, in teoria dovrebbe essere chiamato una volta sola, poi tutto dovrebbe funzionare coi cookie caricati da disco.

**Comment by dentaku65** [comment]
Sei un grande!

**Comment by dentaku65** [comment]
Il canale è stato aggiunto, ma funzionerà dalla prossima release. Grazie a tutti!
