### ISSUE TITLE
download ...

### ISSUE THREAD

**Issue by zizzulone** [streamondemand/plugin.video.streamondemand#130]
Con l'ultima versione il download non funziona piu', mi dice film non trovato mi fa mettere un altro nome e poi parte il download ma non lo salva piu' nella solita cartella ...
ho rimesso la 5.4.5 e funziona correttamente.

**Comment by costaplus** [comment]
Ciao,
sappiamo già del problema ... speriamo di riuscire a risolvere presto il problema!

**Comment by Dr-Zer0** [comment]
fixed
