### ISSUE TITLE
Non riesco ad aggiungere alla libreria e nemmeno scaricare

### ISSUE THREAD

**Issue by orisystech** [streamondemand/plugin.video.streamondemand#135]
Ho un problema con la versione 5.4.6 non riesco a scaricare o aggiungere alla libreria le serie tv. la stessa cosa accade con i film, non c'è la voce "aggiungi alla libreria". in particolare con le serie tv mi quando schiaccio su "aggiungi alla libreria" oppure "scarica serie" non succede niente, infatti se vado a vedere nella libreria mi dice che non ci sono episodi.

mi da questi errori kodi:

 ERROR: GetDirectory - Error getting plugin://
15:45:52.606 T:140030978147648   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
15:46:10.327 T:140030479685376 WARNING: CSkinInfo: failed to load skin settings
15:46:10.327 T:140030479685376   ERROR: EXCEPTION: XML File for Window is missing
15:46:10.329 T:140030479685376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/home/orisystech/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 50, in <module>
                                                window = navigation.get_window_for_item( item )
                                              File "/home/orisystech/.kodi/addons/plugin.video.streamondemand-pureita-master/navigation.py", line 294, in get_window_for_item
                                                window = window_channels.ChannelWindow("banner.xml",plugintools.get_runtime_path())
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
15:46:10.724 T:140029370869504 WARNING: CSkinInfo: failed to load skin settings
15:46:10.724 T:140029370869504   ERROR: EXCEPTION: XML File for Window is missing
15:46:10.724 T:140029370869504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: XML File for Window is missing
                                            Traceback (most recent call last):
                                              File "/home/orisystech/.kodi/addons/plugin.video.streamondemand-pureita-master/default.py", line 50, in <module>
                                                window = navigation.get_window_for_item( item )
                                              File "/home/orisystech/.kodi/addons/plugin.video.streamondemand-pureita-master/navigation.py", line 294, in get_window_for_item
                                                window = window_channels.ChannelWindow("banner.xml",plugintools.get_runtime_path())
                                            RuntimeError: XML File for Window is missing
                                            -->End of Python script error report<--
15:48:46.078 T:140030488078080  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
15:49:02.497 T:140030978147648   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
15:49:13.366 T:140020160460544   ERROR: /home/orisystech/.kodi/addons/plugin.video.streamondemand/lib/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                              warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
15:50:44.065 T:140030488078080   ERROR: Previous line repeats 4 times.
15:50:51.281 T:140029280118528   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://www.streamblog.cohttps//www.streamblog.me/uploads/posts/2015-03/1425651767_1414414958_437.jpg

**Comment by costaplus** [comment]
Ciao, mi soiace deluderti anche se gli stessi problemi li ha SoD, putroppo i log fanno riferimento alla PureIta che non seguiamo nel dettaglio noi.

**Comment by dentaku65** [comment]
pureita è un altro addon
