### ISSUE TITLE
non riesco ad aggiungere film e serie tv alla libreria

### ISSUE THREAD

**Issue by orisystech** [streamondemand/plugin.video.streamondemand#137]
mi scuso nel voler riaprire questo argomento. 
non riesco ancora ad aggiungere serie tv alla libreria se le prendo da canali che non siano guardaserie. per quanto riguarda i film non trovo neanche la voce per aggiungerli. Kodi mi da un sacco di errori per quanto riguarda STREAMONDEMAND (non streamondemand pure ita). Un errore in particolare è quello in cui mi dice che manca una libreria anche se l'ho installata. uso archlinux come sistema operativo.
gli errori sono questi:
 
12:36:41.013 T:140177531991808   ERROR: Previous line repeats 6 times.
12:36:41.013 T:140177531991808   ERROR: /home/orisystech/.kodi/addons/plugin.video.streamondemand/lib/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                              warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
12:38:31.262 T:140178223351552   ERROR: Previous line repeats 2 times.
12:38:31.262 T:140178223351552 WARNING: CSkinInfo: failed to load skin settings
12:38:37.046 T:140178068862720   ERROR: /home/orisystech/.kodi/addons/plugin.video.streamondemand/lib/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                              warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
12:38:53.961 T:140179835516224   ERROR: Previous line repeats 1 times.
12:38:53.961 T:140179835516224   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?ewogICAgImNhdGVnb3J5IjogIkxpYnJlcmlhIHNlcmllIiwgCiAgICAiZmFuYXJ0IjogImh0dHA6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvbDZkbmlUbjM2RFNJMVlwUDhEMWpnMm4wSENjLmpwZyIsIAogICAgImluZm9MYWJlbHMiOiB7fSwgCiAgICAidGh1bWJuYWlsIjogIiIsIAogICAgInRpdGxlIjogIk5vbiBjaSBzb25vIGVsZW1lbnRpIGRhIHZpc3VhbGl6emFyZSIsIAogICAgInRvdGFsSXRlbXMiOiAwCn0%3d
12:38:53.962 T:140179835516224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?ewogICAgImNhdGVnb3J5IjogIkxpYnJlcmlhIHNlcmllIiwgCiAgICAiZmFuYXJ0IjogImh0dHA6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvbDZkbmlUbjM2RFNJMVlwUDhEMWpnMm4wSENjLmpwZyIsIAogICAgImluZm9MYWJlbHMiOiB7fSwgCiAgICAidGh1bWJuYWlsIjogIiIsIAogICAgInRpdGxlIjogIk5vbiBjaSBzb25vIGVsZW1lbnRpIGRhIHZpc3VhbGl6emFyZSIsIAogICAgInRvdGFsSXRlbXMiOiAwCn0%3d) failed
12:38:56.007 T:140179835516224   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?ewogICAgImNhdGVnb3J5IjogIkxpYnJlcmlhIHNlcmllIiwgCiAgICAiZmFuYXJ0IjogImh0dHA6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvbDZkbmlUbjM2RFNJMVlwUDhEMWpnMm4wSENjLmpwZyIsIAogICAgImluZm9MYWJlbHMiOiB7fSwgCiAgICAidGh1bWJuYWlsIjogIiIsIAogICAgInRpdGxlIjogIk5vbiBjaSBzb25vIGVsZW1lbnRpIGRhIHZpc3VhbGl6emFyZSIsIAogICAgInRvdGFsSXRlbXMiOiAwCn0%3d
12:38:56.008 T:140179835516224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?ewogICAgImNhdGVnb3J5IjogIkxpYnJlcmlhIHNlcmllIiwgCiAgICAiZmFuYXJ0IjogImh0dHA6Ly9pbWFnZS50bWRiLm9yZy90L3Avb3JpZ2luYWwvbDZkbmlUbjM2RFNJMVlwUDhEMWpnMm4wSENjLmpwZyIsIAogICAgImluZm9MYWJlbHMiOiB7fSwgCiAgICAidGh1bWJuYWlsIjogIiIsIAogICAgInRpdGxlIjogIk5vbiBjaSBzb25vIGVsZW1lbnRpIGRhIHZpc3VhbGl6emFyZSIsIAogICAgInRvdGFsSXRlbXMiOiAwCn0%3d) failed
12:39:08.419 T:140175845877504   ERROR: /home/orisystech/.kodi/addons/plugin.video.streamondemand/lib/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                              warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
12:39:52.198 T:140175812306688   ERROR: Previous line repeats 2 times.
12:39:52.198 T:140175812306688   ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for http://www.streamblog.cohttps//www.streamblog.me/uploads/posts/2015-03/1425651767_1414414958_437.jpg
12:40:19.251 T:140175845877504 WARNING: CSkinInfo: failed to load skin settings
12:40:56.200 T:140175845877504   ERROR: /home/orisystech/.kodi/addons/plugin.video.streamondemand/lib/fuzzywuzzy/fuzz.py:33: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
                                              warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
12:43:58.399 T:140179835516224   ERROR: Previous line repeats 2 times.

ripeto, per chiarezza, che sono errori di STREAMONDEMAND perchè streamondemand pure ita è disinstallato.

**Comment by Bonobomagno** [comment]
Vedo più problemi. 
Il più semplice:
cambia distro, o cambia repo. Ti serve qualcosa di nuovo per python.
O cmq installa python-Levenshtein, così dice il warning.

Noto anche un errore nella ricostruzione dell'url.
Intanto prova a mettere la libreria di sopra.

**Comment by orisystech** [comment]
ho installato anche python-Levenshtein ma non cambia nulla. lo stesso problema me lo da su windows. i log su windows non li ho guardati. per quanto riguarda la distro arch è una rolling release quindi è tutto super aggiornato.

**Comment by costaplus** [comment]
Ciao fuzzywuzzy è una libreria inseta in SoD Quindi anche installando altro non cambia il problema!

**Comment by dentaku65** [comment]
Mega merge della libreria oggi, dovrebbe funzionare anche adesso aggiornandosi o bisogna aspettare la prossima release
