### ISSUE TITLE
Collegamenti mancanti

### ISSUE THREAD

**Issue by phede86** [streamondemand/plugin.video.streamondemand#138]
Mi capita spesso di non trovare dei link su cb01  ma é falso perché con il browser si vedevo e sono presenti.

**Comment by dentaku65** [comment]
@phede86 per piacere metti i riferimenti del problema; cosa pensi che dobbiamo spulciare tutti i link di cb01 per darti una risposta? Considera inoltre che molti link hanno un "offuscatore" e quindi il nostro codice non riesce a risolvere la destinazione, questo è normale. Sii preciso quando inserisci una issue in Github.
