### ISSUE TITLE
Kodi freezes on exit with add-on installed

### ISSUE THREAD

**Issue by rssluca** [streamondemand/plugin.video.streamondemand#143]
This add-on causes Kodi to freeze on exit. Tried several times installing and uninstalling the add-on and Kodi exits fine when streamondemand is not installed.

**Comment by MrTruth0** [comment]
Have you tried to reinstall kodi ?

**Comment by dentaku65** [comment]
Which platform? Which OS? Kodi version? You must place logs on Kodi forum or platform forum in case of freeze

**Comment by dentaku65** [comment]
only on windows https://github.com/streamondemand/plugin.video.streamondemand/issues/156
