### ISSUE TITLE
Connettore Mega

### ISSUE THREAD

**Issue by dentaku65** [streamondemand/plugin.video.streamondemand#146]
Il canale cinesuggestions utilizza esclusivamente come connettore Mega che pero' non funziona nella sua integrazione con /lib/Crypto 

Mi chiedevo se ci fosse la possibilità o di sistemare Crypto o di utilizzare /lib/pyaes che ha messo su il Doc

Il problema con Crypto è che l'import di _AES non viene proprio trovato

**Comment by dentaku65** [comment]
Ok. Per il connettore Mega nei sistemi linux basta installare la libreria crypto di python; esempio in OSMC
`sudo apt-get install python-crypto`
e rinominare is SOD la dir /lib/Crypto in /lib/_Crypto

Difatti tale libreria /lib/Crypto è valida solo per windows (che non ho provato); l'ideale sarebbe inserire un messaggio o un ignore su /lib/Crypto se non si è in un sistema win.

**Comment by Dr-Zer0** [comment]
funziona con pyaes

**Comment by dentaku65** [comment]
Con pyaes kodi17+osmc+rpi2 ricevo questo errore
http://pastebin.com/8UU05vRF

**Comment by Dr-Zer0** [comment]
sistemato

**Comment by dentaku65** [comment]
ehm,,, :-)
in effetti intercetta il video ma si ferma ad un secondo e rimane li con sfondo nero

**Comment by Dr-Zer0** [comment]
@dentaku65 direi che è un problema di risorse hw: il rpi è troppo scarso.
Su pc il video parte tranquillamente, sarebbe da provare su box android che ha un hw più potente di rpi.
Chi si offre di fare questa prova?

**Comment by dentaku65** [comment]
@Dr-Zer0 anche con android parte dopo averci pensato un po' e si ferma ad 1 secondo con schermata nera; il tablet è il fire di amz con cyanogenmod... quindi anche lui potrebbe essere non adatto per performance un po' più elevate

**Comment by Dr-Zer0** [comment]
@dentaku65 da python è possibile capire in che s.o. sta girando kodi. Può valer la pena per android usare pyaes, per win la lib inclusa e per gli altri far installare pycrypto (su mac si può fare)?

**Comment by dentaku65** [comment]
@Dr-Zer0 non ho idea per mac...credo che ci sia anche lì il pacchetto py-crypto, ma ho il dubbio che Kodi non utilizzi il python di sistema lì sopra... ocio che il /lib/megaserver con Kodi sull'RPI non funge con le modifiche fatte per pyaes, bisogna metterci il megaserver precedente ed eliminare (o rinominare) la dir /lib/Crypto... questo giochetto non si puo' fare con pyaes perchè pyaes serve anche per altri canali e non solo per il connettore mega

**Comment by MrTruth0** [comment]
@dentaku65 Credo che il metodo per farlo funzionare sia meglio scriverlo sia sul forum e sia sulla pagina facebook (Chi ha accesso ovviamente).

**Comment by dentaku65** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=37&t=8871
