### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by dentaku65** [streamondemand/plugin.video.streamondemand#148]
Il file descarga.py contiene questa stringa richiamata tre volte che inficia il download delle serie
`"%dx%0.2d - %s"` 
L'errore relativo 
http://pastebin.com/iQNRxLk5

In sostanza:

> %d format: a number is required, not str

Provato int(), float(), int(float()) nulla!
Qualcuno puo' illuminarmi?

**Comment by costaplus** [comment]
Ciao Den ho fatto un test mettendo a manina quei valori... va oltre ..bellissimo, peccato che poi esce fuoir che manca un library in platformcore... ti risulta?

**Comment by dentaku65** [comment]
@costaplus mmm no, postami le modifiche pls

**Comment by thehutt61** [comment]
@dentaku65 
Salve ragazzi
scoperto l'arcano... il problema non sta sul modulo "descargas.py" ma sui moduli dei canali...
Io ho fatto qualche prova con "SerieHD" e questo è quello che ho scoperto 

Il modulo "descargas.py" si aspetta che gli episodi (e solo quelli) gli vengano passati col parametro contentType="episode"

Invece gli episodi gli vengono passati con contentType="tvshow" e l'unica riga che arriva con contentType="episode" è quella "Aggiungi alla libreria" ed è questo che causa l'errore "%d format: a number is required, not str" in quanto non riesce a trovare il numero della stagione e il numero dell'episodio.

Faccio qualche altra prova e vi faccio sapere se la soluzione funziona.

Ciao

**Comment by dentaku65** [comment]
fixed by doc
