### ISSUE TITLE
Download issue #2

### ISSUE THREAD

**Issue by thehutt61** [streamondemand/plugin.video.streamondemand#155]
#148 

@dentaku65 
il problema del download esiste anche per i film... in questo caso il contentType deve essere impostato a "movie"

**Comment by costaplus** [comment]
Ok @den, bisogna sistemare tutti i canali con film quindi ?

**Comment by dentaku65** [comment]
@thehutt61 per piacere mi metti un canale di esempio?

**Comment by Dr-Zer0** [comment]
Il download dei film parte senza problemi e non c'è bisogno di mettere il contentType (lo mette già infoSod). Se qualche canale non usa infoSod per le locandine bisogna sistemare.

**Comment by dentaku65** [comment]
@Dr-Zer0 ok
