### ISSUE TITLE
Alcuni problemi nella nuova versione 5.4.8

### ISSUE THREAD

**Issue by axlt2002** [streamondemand/plugin.video.streamondemand#156]
Ciao,

Riporta qui per comodità quanto scritto anche sul forum. In sostanza segnalo i seguenti tre problemi:
- Mancato aggiornamento dei server/canali all'avvio
- Kodi si blocca all'uscita
- Non apertura degli stream da rapidvideo.com

Al seguent link trovate il log ottenuto abilitando il debug di SOD: http://pastebin.com/kwCuQ94R. La macchina attuale su cui sto facendo le prove monta Windows 7 x86.

Da una prima "lettura" mi sento di dire che:

- La routine iniziale di update dei canali/server sembra non essere chiamata
- Quando Kodi esce, il _library_service.py_ rimane "appeso" in quanto viene visualizzato il seguente messaggio:

_16:13:22.934 T:5300   ERROR: CPythonInvoker(1, C:\Program Files\Kodi\portable_data\addons\plugin.video.streamondemand\library_service.py): script didn't stop in 5 seconds - let's kill it_

e solitamente Kodi non ci riesce ad ucciderlo (qualche volta sì ma solo dopo un bel pò di tempo).

In aggiunta a tutto questo, segnalo anche l'impossiblità di vedere i video da rapidvideo.com: il log riporta il tentativo di apertura di uno stream ma senza successo. Queso il link dello stream video (correttamente ottenuto ma poi non aperto): https://www.rapidvideo.com/embed/1Dl0Knox

**Comment by costaplus** [comment]
Dal log mi sembra di capire che usi win 7 o sbaglio ?
Prova ad avviare kodi come amministratore tasto destro mouse...

**Comment by MrTruth0** [comment]
Ho provato a vedere e i video su rapidvideo mi funzionano, mentre gli altri due problemi li ho pure io, sia con Windows 10 Kodi 17 e Raspberry pi 3 Con Kodi 16.1

**Comment by axlt2002** [comment]
Ciao, grazie dei vostri feedbacks.
@costaplus Sì, utilizzo Windows 7 ma avviando Kodi come amministatore non cambia nulla (mi riferisco ai primi due problemi)
@MrTruth0 Potresti fare una prova con l'esatto episodio relativo al link che ho messo (https://www.rapidvideo.com/embed/1Dl0Knox)? Si tratta della puntata 8 stagione 1 di Stanger Things presa da SerieHD...qui puoi trovare gli screenshots relativi all'errore (http://imgur.com/a/Nrkb7).

**Comment by MrTruth0** [comment]
Ok, con quello da il tuo stesso problema

**Comment by axlt2002** [comment]
Grazie per la prova. Purtroppo su quelle parti del codice non so metterci le mani...spero sia possibile risolvere.

**Comment by dentaku65** [comment]
Per rapidvideo ci vorrebbe un link funzionante che, mi pare Mrtruth0 ha trovato, da comparare con quello non funzionante, magari è solo un'struzione da mettere sul connettore, sempre che il link indicato via browser funzioni.

Per Win non saprei, non lo uso; Kodi 17 su rpi1, 2 e 3 a me non si blocca (uso OSMC)

Per gli aggiornamenti dei canali/server purtroppo è vero, spero a breve il fix che porterà adun'altra release.

**Comment by MrTruth0** [comment]
@dentaku65 Avevo sbagliato prima, Il link che avevo utilizzato io faceva uso di rapidvideo.org (rapidvideo.py), quando ho provato l'ep 8 di Stranger things ho notato che utilizzava rapidvideocom e non l'altro adesso stavo provando con un link funzionante di rapidvideo.com che sarebbe https://www.raptu.com/embed/Ov9MzKU3 , pare che i link di rapidvideo.com reindirizzano a raptu.com e quindi da errore, ho risolto cambiando la variabile url nel file rapidvideocom.py in find_videos da https://www.rapidvideo.com/embed/%s in https://www.raptu.com/embed/%s

**Comment by Dr-Zer0** [comment]
Ho sistemato l'update di canali e server.

A me kodi non rimane mai appeso durante la chiusura, non vedo come possa capire l'errore e sistemarlo.

**Comment by axlt2002** [comment]
Grazie MrTruth0 e Dr-Zer0 per il vostro consueto e prezioso aiuto!

@Dr-Zer0 che sistema operativo utilizzi sulla macchina dove non riscontri il problema? Ora provo ad installare la master con le ultime correzioni...non vorrei che il fatto di restare appeso possa avere a che fare con l'update dei canali. Vi faccio sapere a breve...

**Comment by Dr-Zer0** [comment]
@axlt2002 ho solo macchine con linux, per me non esiste altro. Uso varie distro e non riscontro il problema.

**Comment by axlt2002** [comment]
Se si dovesse rilasciare una nuova release, ricordiamoci di modificare il file settings.xml in resource con il numero di versione corretto per evitare lo scaricamento della stessa versione alla prima installazione. ;)

**Comment by axlt2002** [comment]
Ok, capito, sei uno cazzuto! ;)
Non saprei che dire: dal log sembrano esserci problemi con il file _library_service.py_...Magari posso indagare sul forum di pelisalacarta; non vorrei fosse un qualcosa "ereditato" dal suo codice...

**Comment by MrTruth0** [comment]
Ho appena installato kodi 17.1 e SOD su un portatile con windows 8.1 e anche qua c'è il problema del freeze all'uscita, su raspberry (con OpenELEC) ho provato a spegnerlo e non da questo problema ... Invece con un altro portatile con CPU Amd e Kodi 16.1 (Non posso usare il 17 perchè ha problemi con le apu amd e crasha) e pure questo con Windows 8.1 non si freeza all'uscita.

**Comment by axlt2002** [comment]
Grazie per il tuo feedback MrTruth0! Sembra il problema sia circoscritto a Windows combinato con la versione 17 di Kodi...non che questo mi rincuori...provo ad intallare la 16.1 sulla stessa macchina e vedo se si può confermare la deduzione...
Per quanto riguarda il tema del crash, usi per caso la APU in Dual Graphics con una GPU discreta?

**Comment by MrTruth0** [comment]
@axlt2002 No, Solo una APU molto scarsa, E1-2100 da 1 GHz però per kodi va bene e spero che il problema di Kodi 17 con le APU AMD venga sistemato ...

**Comment by axlt2002** [comment]
@MrTruth0 Te lo chiedevo perchè io sul mio Media Center ho una APU A8-6500 in Dual Graphics con una Radeon HD 6670. Per non far crashare Kodi ho dovuto disabilitare il Dual Graphic (solo per Kodi ovviamente). Non credo che sia tra le priorità degli sviluppatori di Kodi il problema con le APU...purtroppo...

Nel mentre, "buone" notizie: l'ultima versione di SOD mi fa stallare anche Kodi 16.1 (Windows 7).

**Comment by dentaku65** [comment]
@axlt2002 thx for the info x settings.xml!
@Dr-Zer0 thx for the quick fix!

**Comment by axlt2002** [comment]
You are more than welcom dentaku65! ;)

Ok, penso di aver scoperto il problema del freeze...ma ovviamnete non so come risolverlo. Allora, utilizzando l'ultima master ho notato che SOD fa congelare Kodi quando non si ha una connessione ad Internet...le prove fatte con la master un'ora fa su Kodi 17 e 16.1 erano "offline" e mi davano il problema. Attivando il WiFi, ho potuto verificare l'aggiornamento dei canali all'avvio ed il fatto che Kodi si chiude senza problemi.

Dando uno sguardo al file incriminato nel log (il _library_service.py_), ho notato la seguente parte di codice:

if scrapertools.wait_for_internet(retry=10)

Che sia quindi stata fatta una modifica allo scrapertools che lo mandi in loop nel caso non ci sia una connessione ad Internet?
@MrTruth0 il SOD che hai provato con Kodi 17 e che freezava era l'attuale master o la 5.4.8? Il PC era collegato ad Internet?

**Comment by MrTruth0** [comment]
Era la 5.4.8 ed era collegato ad internet (Tutti i test che ho fatto erano con internet attivo)

**Comment by axlt2002** [comment]
Ok, puoi provare con la master attuale per favore? La 5.4.8 aveva l'aggiornamento dei canali che non funzionava...

**Comment by MrTruth0** [comment]
Cancellato tutto di SOD, installata la master e non mi si blocca più, su KODI 17.1 e Windows 10.

01:13:57.942 T:1856   DEBUG: CPythonInvoker(6, D:\AppData\Roaming\Kodi\addons\plugin.video.streamondemand\library_service.py): script termination took 0ms

**Comment by axlt2002** [comment]
Ottimo...puoi provare senza connessione ad Internet?

**Comment by MrTruth0** [comment]
Ok, senza connessione crasha

**Comment by axlt2002** [comment]
Perfetto! Lo abbiamo beccato...sul come risolverlo, vista l'ora, non riesco a pensare a nulla... ;)

Secondo me è legato al metodo _scrapertools.wait_for_internet_ chiamato in _library_service.py_...ho fatto una verifica nel codice di pelisalacarta e non ve ne è traccia...

Direi che per oggi, almeno per me, può bastare...grazie dell'aiuto e a domani!

**Comment by dentaku65** [comment]
@axlt2002 il wait_for_inernet serve. Si tratta di una routine che aspetta di essere on-line per fare gli update di SOD. Era presente anche sulla 16 e comunque da molto tempo

**Comment by axlt2002** [comment]
@dentaku65 sì, esatto, ho visto il metodo in questione anche nelle versioni precedenti. Magari è cambiato qualcosa relativamente alla sua chiamata in _library_service.py_. Di sicuro qualcosa di diverso c'è...prima tutto funzionava (dubito che nessuno abbia mai aperto Kodi senza essere connesso ad Internet almeno una volta).

**Comment by axlt2002** [comment]
RISOLTO! Ho debuggato il codice stile "vecchia maniera" ed ho capito tutto.
Il metodo wait_for_internet verifica la presenza di una connessione ad Internet ogni 30 secondi per 10 volte, per un totale di 300 secondi (e cioè 5 minuti). Al termine dei 5 minuti ritorna un False e lo script library_service.py riprende la sua strada. Nel caso di assenza di connessione, quindi, per non avere l'errore, bisogna chiudere Kodi dopo almeno 5 minuti, altrimenti lo script ibrary_service.py risulta appeso (in realtà sta aspettando la risposta da parte del metodo wait_for_internet) e Kodi non riesce a "killarlo" correttemente (probabilmente Linux ha una gestione più efficiente di questi casi).
Insomma, siccome vedo improbabile che un utente esca da Kodi prima di 5 minuti e soprattutto senza una connessione ad Internet attiva, non vi è alcun baco da risolvere... ;)
Una volta letta la spiegazione, potete chiudere l'issue (credo ve ne sia anche un altro simile da chiudere).
Grazie a tutti per la collaborazione!

**Comment by thehutt61** [comment]
Si potrebbe provare a modificare la riga 529 di scrapertools.py così:
        if count >= retry or xbmc.abortRequested:
in modo che "wait_for_internet" ritorni un False anche nel caso sia stata richiesta una uscita da Kodi prima che trascorrano i 5 minuti

**Comment by Dr-Zer0** [comment]
@thehutt61 
xbmc.abortRequested non va bene per kodi 17, andava bene per le versioni vecchie.
Bisogna fare riferimento a questo: http://kodi.wiki/view/Service_add-ons

**Comment by axlt2002** [comment]
@thehutt61 la tua modifica risolverebbe in parte il problema nel senso che quel check viene eseguito ogni trenta secondi...quindi a meno che non si chiuda Kodi "nei dintorni" dello scadere dei 30 secondi, il problema si presenta comunque.
Una soluzione potrebbe essere quella di diminuire da 30 a 5 secondi la periodicità del check (ripetendolo 60 volte per mantenre il tempo massimo di 5 minuti)...non riesco però a valutare se questo possa avere un impatto sulle performance in generale di Kodi.
Che ne pensate?

**Comment by thehutt61** [comment]
Scusate se non mi sono fatto sentire prima ma Tiscali ha deciso di lasciarmi a piedi con l'ADSL da venerdì...

ho modificato la funzione wait_for_internet e così sembra funzionare...
ho aggiunto anche la gestione per le versioni di kodi precedenti alla 14 nel caso fosse necessario (anche se confesso di non averla provata)

questa è la funzione modificata:

`def wait_for_internet(wait=30, retry=5):
    import xbmc
    import sys
    version_xbmc = int(xbmc.getInfoLabel("System.BuildVersion").split(".", 1)[0])

    if version_xbmc >= 14:
        monitor = xbmc.Monitor()  # For Kodi >= 14
    else:
        monitor = None  # For Kodi < 14

    if monitor:
        count = 0
        while True:
            if internet():
                return True
            count += 1
            if count >= retry or monitor.abortRequested():
                return False
            if monitor.waitForAbort(wait):
                sys.exit()
    else:
        count = 0
        while True:
            if internet():
                return True
            count += 1
            if count >= retry or xbmc.abortRequested:
                return False
            xbmc.sleep(wait)
`

**Comment by Dr-Zer0** [comment]
Ho già committato il codice funzionante (assomiglia al codice di @thehutt61 senza kodi < 14), dateci un'occhiata.

**Comment by thehutt61** [comment]
@Dr-Zer0 
Prima di apportare queste ultime modifiche avevo provato anch'io la tua soluzione ma, quantomeno sulla mia installazione di kodi (kodi 17 su win 7), succede una cosa strana...
Effettivamente, alla richiesta di uscita da kodi, il loop di wait_for_internet si interrompe subito e il controllo ripassa a library_service.py dove però sembra non venga più riconosciuta la precedente richiesta di abort e quindi viene fuori l'errore "script didn't stop in 5 seconds - let's kill it" con conseguente problema di chiusura di kodi.
Eseguendo invece sys.exit() in caso sia stato richiesta l'uscita mentre esegue il loop di wait_for_internet, l'errore non viene più fuori e kodi si chiude dopo qualche secondo.
Succede solo a me?

**Comment by Dr-Zer0** [comment]
@thehutt61 non avendo win per fare delle prove non mi è mai capitato che kodi vada in stallo dopo che il controllo ripassa a library_service.py.
Il comportamento è strano: se wait_for_internet torna False in library_service non viene fatto niente.

**Comment by axlt2002** [comment]
Ciao a tutti,
Scusate la mia latitanza ma sono stato via per lavoro.
@Dr-Zer0 la modifica è contenuta nella nuova master? Onestamente non ho più usato Kodi offline, quindi non ho potuto appurare l'eventuale persistere del baco.

P.S.: Ho aperto un nuovo issue per un errore all'avvio di SOD con l'ultima master.

**Comment by axlt2002** [comment]
Ciao, ho notato che è stato ereditato (non so quando) da pelisalacarta il codice di _library_service.py_ che dovrebbe risolvere il problema. La modifica è simile a quella effettuata oer il metodo _wait_for_internet_:

    # Se ejecuta ciclicamente
    if config.get_platform(True)['num_version'] >= 14:
        monitor = xbmc.Monitor()  # For Kodi >= 14
    else:
        monitor = None  # For Kodi < 14

Onestamente se lavoro offline, il problema persiste...
Voi avete avuto modo di darci ancora uno sguardo?
