### ISSUE TITLE
Prblemi con il dominio "cineblog01.cc/anime"

### ISSUE THREAD

**Issue by Elvitek** [streamondemand/plugin.video.streamondemand#159]
Sia provando a vedere 2 anime che ho nei preferiti e sia cercando un nuovo anime da quel dominio, fa la ricerca, trova l'anime ma al suo interno non ci sono gli episodi. A volte questo errore lo fa anche con le serie tv, sempre da cb01 e ad esempio cercando Breaking Bad.

**Comment by dentaku65** [comment]
fixed by MrTruth0
