### ISSUE TITLE
last_search

### ISSUE THREAD

**Issue by dentaku65** [streamondemand/plugin.video.streamondemand#165]
Anche se il last_search è disabilitato, vedi ultime righe xml
https://raw.githubusercontent.com/streamondemand/plugin.video.streamondemand/master/channels/buscador.xml
risulta sempre presente nelle ricerche; il last_search interferisce sia con le ricerche salvate che con l'update dei canali/server (facendo comparire randomicamente in maniera fissa la progress bar in alto).

In buona sostanza il last_search non sbianchetta l'ultima ricerca ll'interno della finestra di ricerca sia per la ricerca in tutti i canali che per quelle via tmdb.

E' possibile rimuovere completamente questa feature? Pensavo di averlo fatto io, ma è ricomparsa :-(

**Comment by Dr-Zer0** [comment]
@dentaku65 secondo me hai il last_search abilitato, non basta metterlo nell'xml bisogna anche cancellare i file sotto .kodi/userdata/addon_data/plugin.video.streamondemand/settings_channels/
perchè se ci sono questi file gi xml non vengono consultati.

**Comment by dentaku65** [comment]
@Dr-Zer0 ah ecco; ma se modifichiamo il launcher.py cosi:
`            elif item.action == "search":
                logger.info("streamondemand.platformcode.launcher search")

                last_search = ""
                last_search_active = config.get_setting("last_search", "buscador")

                tecleado = platformtools.dialog_input(last_search)
                if tecleado is not None:

                    # TODO revisar 'personal.py' porque no tiene función search y daría problemas
                    # DrZ3r0
                    itemlist = channel.search(item, tecleado.replace(" ", "+"))
                else:
                    itemlist = []
                
                platformtools.render_items(itemlist, item)`

**Comment by Dr-Zer0** [comment]
@dentaku65 possiamo modificare il launcher come hai scritto, però se confronti il tuo codice con quello che c'è adesso vedrai che fanno esattamente la stessa cosa perché last_search_active = False come impostato nell'xml.
Se permangono dei problemi non è da imputare a questo codice ma a qualcos'altro.

**Comment by dentaku65** [comment]
@Dr-Zer0 l'ho provato sulla mia installazione e il last_search sparisce completamente; l'unica cosa è che non sono sicuro dello snippet modificato che ho postato

**Comment by dentaku65** [comment]
Non so' se è dovuto all'eliminazione del last_search ma quando faccio una ricerca qualsiasi mi compare a corredo anche la progress di update dei canali/server e rimane lì appesa.... non pregiudica alcuna funzione, è solo disturbante visivamente

**Comment by dentaku65** [comment]
@Dr-Zer0 il problema della progress bar persistente sembra esserci solo nelle installazioni RPI; questa è la parte del log che potrebbe essere incriminata:
https://pastebin.com/jcg6U5Xf

**Comment by MrTruth0** [comment]
@dentaku65 Se è quello l'errore sembra essere identico a questo problema: 
http://www.mimediacenter.info/foro/viewtopic.php?f=37&t=8901

**Comment by dentaku65** [comment]
@Dr-Zer0 fixed by your fix; changed mutithread from 4 to 10 on update_servers and update_channels
