### ISSUE TITLE
Cancellazione automatica del file scaricato non voluta

### ISSUE THREAD

**Issue by Elvitek** [streamondemand/plugin.video.streamondemand#167]
Buonasera ragazzi. Ho notato che scaricando degli anime (ad esempio una puntata de "L'Attacco dei Giganti FULL ITA" dal cb01anime con openload), finisce il download al 100% ma a fine download il file si cancella da solo facendo rimanere solo il file della lista che segna il 100%.  Ho provato a cambiare i percorsi e ho notato che ad inizio download, il file che si sta scaricando si crea ed è visualizzabile (non è completo quindi finisce subito), ma appena arriva al 100%, il file si cancella. Ora non ho provato se fa lo stesso con un film o un episodio di una serie tv ma con gli anime fa così. Potete aiutarmi a risolvere o potete controllare se a voi fa la stessa cosa? Grazie.

**Comment by MrTruth0** [comment]
Nella cartella library non lo trovi ? dopo che il download finisce viene spostato nella libreria (Di default sta in C:\Users\TUONOME\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.streamondemand\library\CINE)

**Comment by Elvitek** [comment]
Partendo dal fatto che uso SoD su una smart box, sono andato nella cartella che mi hai detto ed i file c'erano ma al di fuori della cartella CINE ma nella cartella library, quindi può darsi che non essendoci una cartella apposita per gli anime, me li mette lì non facendomeli vedere nè su Kodi e nè sul vostro add-on.. Come risolvo?

**Comment by dentaku65** [comment]
@Elvitek hai aggiornato tutti i file presenti in github attualmente con quelli prsenti sulla smartbox? Sono stati fatti dei lavori enormi che dovrebbero aver sistemato il problema dei dl.

**Comment by Elvitek** [comment]
Purtroppo si, infatti ogni volta che esce un nuovo fix lo installo al volo.. Va bene dai, aspetterò la prossima release, grazie per le risposte.

**Comment by Elvitek** [comment]
Nella ricerca dei film, non vengo più visualizzati le ricerche dei film tramite CB01.. Ci sono 4 o 5 "altadefinizione" e CB01 e altri non ci sono più. Potete risolvere? Grazie.

**Comment by Elvitek** [comment]
Anche nella versione 5.4.9 con l'ultimo fix (il numero 26), l'anime scaricato da cb01anime viene messo nella cartella "library" e non in "CINE" o "SERIES", quindi è non visibile nella libreria dentro SoD, nemmeno dopo un riavvio.

**Comment by Elvitek** [comment]
Ho provato a scaricare un anime con SoD 5.5.0 (fix 15) e finalmente il file me lo mette nella libreria nella sezione "visualizza download terminati".  Problema risolto e potete chiudere il topic.

**Comment by costaplus** [comment]
@Eviltek ho creato quella modifica per tutti quelli che lamentavano giustamente la sparizione dei file scaricati, speriamo che sia la volta buona!

**Comment by Elvitek** [comment]
Ed hai fatto bene perché così funziona alla grande tra la visualizzazione del file direttamente da Kodi e non da un'app explorer ed i file vengono anche cancellati definitivamente, quindi complimenti.
