### ISSUE TITLE
Non viene eliminato file video scaricato

### ISSUE THREAD

**Issue by sebastiano93** [streamondemand/plugin.video.streamondemand#169]
Pare che non ci sia un modo per eliminare i video scaricati aggiunti alla libreria. Eliminando il film dalla libreria dopo aver fatto il download, il file video effettivo resta nella cartella 'library'

**Comment by costaplus** [comment]
Mi sembra che ora abbia sistemato la storia della cartella library, confermi sebastiano93 ?
