### ISSUE TITLE
Cineblog01

### ISSUE THREAD

**Issue by MrTruth0** [streamondemand/plugin.video.streamondemand#171]
Non è possibile riprodurre video da alcuni server su Cineblog01

I server certi che non funzionano sono: 

- Abysstream
- Backin
- WStream

Errore: http://pastebin.com/wcDFCga4

**Comment by dentaku65** [comment]
In cb01 questi connettori sono nascosti da link obfuscators che 9 volte su 10 inficiano il raggiungimento del vero url

**Comment by Dr-Zer0** [comment]
abysstream e wstream funzionano. Se su cb01 a volte danno problemi è per quanto detto da @dentaku65.
Backing non funziona da parecchio ormai e non c'è stato verso di sistemarlo, se c'è qualcuno che vuole cimentarsi...

**Comment by MrTruth0** [comment]
Ho notato, WStream adesso non mi da problemi ... Allora chiudo.
