### ISSUE TITLE
Aggiungere ritardo di "n" secondi per l'autoupdate dei canali

### ISSUE THREAD

**Issue by iz8mbw** [streamondemand/plugin.video.streamondemand#18]
Ciao.
Come sappiamo allo start streamondemand aggiorna la lista/configurazione dei canali.
Utilizzando streamondemand su OpenELEC ed un un servizio VPN, che allo start / boot attiva la connessione VPN, l'aggiornamento della lista/configurazione dei canali si blocca e poi riparte perché la connessione alla VPN impiega diversi secondi e nello stesso tempo l'aggiornamento della lista/configurazione dei canali si è già avviato.

Questo comporta che la parte iniziale dell'aggiornamento avviene senza VPN, poi la VPN va su e l'aggiornamento si blocca (dato dal cambio IP) e poi continua.
Per evitare che l'aggiornamento della lista/configurazione dei canali avviene in modo parziale/corrotto o senza VPN, è possibile inserire in streamondemand un ritardo (delay) di 60 secondi per esempio (o ancora meglio customizzabile) in modo che allo start (o al boot in caso di OpenELEC) streamondemand aspetta prima di aggiornale la lista (e intanto la VPN è andata su)?

Grazie.

**Comment by dentaku65** [comment]
La tua configurazione non è propriamente standard, quindi il fatto di considerare questa opzione al momento non è una priorità.L'aggiornamento dei canali sarà rivisto alla prossima release con l'intento di aggiornare solo quelli modificati e non tutti i canali tutte le volte come avviene adesso; il network delay è già comunque implementato in SOD, difatti noterai che parte l'aggiornamento dei canali quando effettivamente il sistema riesce a raggiungere la rete pubblica e non immediatamente quando si avvia Kodi; di più: in openElec puoi settare il wait for network nelle impostazioni di sistema.

**Comment by iz8mbw** [comment]
Ciao e grazie per la risposta.
Purtroppo non posso sfruttare l'opzione di OpenELEC di "wait for network" perché ovviamente l'opzione fa riferimento all'interfaccia di rete di default (eth0) e non quella della VPN (tun0). Quell'opzione di OpenELEC è ignara che lì a breve sarà tirata su una nuova interfaccia (tun0) della VPN...

Come dici SOD aggiorna la lista quando vede la rete pubblica UP, ma anche in questo caso sempre e comunque riferita all'interfaccia di rete di default (eth0) e non quella della VPN (tun0).

Sicuramente quello che richiedo non è una priorità, ma per favore valutate la possibilità di inserire questo ritardo nell'update dei canali, non ci sono alternative da trovare in OpenELEC (altrimenti sarebbero state già implementate).
Grazie.
