### ISSUE TITLE
CB01 non funzionante come dovrebbe

### ISSUE THREAD

**Issue by Elvitek** [streamondemand/plugin.video.streamondemand#183]
Nella ricerca dei film, non vengo più visualizzati le i film tramite CB01.. Ci sono 4 o 5 "altadefinizione" che secondo me servono a poco e CB01 e altri "canali" non ci sono più. Potete risolvere? Grazie.

**Comment by dentaku65** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=37&t=8877
