### ISSUE TITLE
cb01 problemi nella ricerca

### ISSUE THREAD

**Issue by 0d1n92** [streamondemand/plugin.video.streamondemand#192]
problemi nella  ricerca cb01 non trova tutti i film presenti nel sito, pur aggiornando a python 3

**Comment by Elvitek** [comment]
Concordo con lui però c'è da spiegarlo meglio. Se io voglio fare una ricerca tramite "Ricerca Globale/Cerca Titolo", troverà il film richiesto ma tranne quello su cb01, mentre se si va su "Scegli una categoria/Top Channels/Cineblog01" il film richiesto si può trovare SOLO scorrendo tra le pagine per anno, per genere o altro ma MAI tramite la scrittura vera e propria del titolo, quindi la ricerca tramite la scrittura del titolo non funziona, nè nella ricerca di tutti i canali e nè solo da cb01. Questo è ciò che fa a me con Kodi 17.1 su una SmartBox, SoD 5.4.9 e l'ultimo fix merge di oggi 23 Marzo.

**Comment by 0d1n92** [comment]
Se cerco film non recenti però tipo titanic lo trova, ma con film recenti no, anche io con smartbox al momento, proverò su raberry aggiornando python, ma anche li ricordo che avevo lo stesso problema.

**Comment by 0d1n92** [comment]
magicamente ha ripreso a funzionare
