### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Pegasoman** [streamondemand/plugin.video.streamondemand#199]
Salve ragazzi ringrazio per il lavoro e vengo al punto, non si può scegliere la risoluzione/grandezza file per il download, es. openload ha 480/720/1080 per un file, chi opera la scelta?

**Comment by jokerulez** [comment]
Quando scegli di scaricare più puntate di una serie utilizza il primo link che trova. Per scaricare alla risoluzione preferita devi scaricare una puntata per volta
