### ISSUE TITLE
Piccioni.... ma credo lo sappiate

### ISSUE THREAD

**Issue by SandraGi** [streamondemand/plugin.video.streamondemand#20]
Piccioni.... ma credo lo sappiate...

**Comment by dentaku65** [comment]
already fixed

**Comment by SandraGi** [comment]
Purtroppo non partono i video di hd openload. Risolve la url, ma poi il nulla

**Comment by Teo007** [comment]
In realtà ha funzionato per un ora e poi nuovamente piccioni...penso ci sia un tira e molla dell'host per aggirare il decode del link :/
