### ISSUE TITLE
Banner aggiornamento server bloccato

### ISSUE THREAD

**Issue by target5** [streamondemand/plugin.video.streamondemand#200]
Salve ragazzi e complimenti per il lavoro; nell'ultima release quando si aggiorna la lista server il banner blu in alto a dx rimane bloccato anche durante la visione di qualsiasi film, così per toglierlo è necessario riavviare Kodi.

**Comment by dentaku65** [comment]
Issue già aperta https://github.com/streamondemand/plugin.video.streamondemand/issues/165
