### ISSUE TITLE
Errore all'avvio di SOD

### ISSUE THREAD

**Issue by axlt2002** [streamondemand/plugin.video.streamondemand#201]
Ciao ragazzi,
Segnalo un errore all'avvio di SOD. [Qui](https://pastebin.com/xP70ENDh) potete trovare il log.
Credo sia qualcosa relativo all'ultima modifica effettuata da dentaku65 per quanto riguarda la xbmc_library.
Buona serata.

**Comment by MrTruth0** [comment]
Ho controllato, e a me SOD non da nessun tipo di errore per "xbmc_library", nel codice ho notato che viene utilizzato xbmc_library senza che venga importato, però non sono sicuro che questo risolva il problema ... ho committato il file con l'import, prova a vedere se ti da ancora quell'errore.

**Comment by axlt2002** [comment]
Ciao MrTruth0!
Ho installato l'ultima master ed il problema non è più presente.
La butto lì...forse a te non dava errore perchè avevi aggiornato un'installazione precedente...
Grazie mille!
