### ISSUE TITLE
Update server infinito

### ISSUE THREAD

**Issue by XychoLight** [streamondemand/plugin.video.streamondemand#208]
Dopo essere entrato nella ricerca globale, il plugin si mette a ricercare all'infinito per dei canali/server, rallentando le prestazioni del raspberry pi 3, oltre al lasciare quel fastidioso banner "Update server: ...." anche mentre si guarda un filmato

**Comment by dentaku65** [comment]
https://github.com/streamondemand/plugin.video.streamondemand/issues/165
