### ISSUE TITLE
Problema da Android TV

### ISSUE THREAD

**Issue by alex78red** [streamondemand/plugin.video.streamondemand#22]
Ciao, ho installato il plugin su Android TV. L'installazione va a buon fine ma se provo ad entrare mi da errore. Ho attivato il debug ed ecco qui il log dell'errore:

******************
22:47:05 T:18446744072077056912  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 1920x1080 @ 60.00 - Full Screen
22:47:05 T:18446744072077056912  NOTICE: GL_VENDOR = ARM
22:47:05 T:18446744072077056912  NOTICE: GL_RENDERER = Mali-T624
22:47:05 T:18446744072077056912  NOTICE: GL_VERSION = OpenGL ES 3.1
22:47:05 T:18446744072077056912  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.10
22:47:05 T:18446744072077056912  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic
22:47:10 T:18446744072077056912  NOTICE: CEGLNativeTypeAndroid: Switching to resolution: 1920x1080 @ 60.00 - Full Screen
22:47:10 T:18446744072077056912  NOTICE: GL_VENDOR = ARM
22:47:10 T:18446744072077056912  NOTICE: GL_RENDERER = Mali-T624
22:47:10 T:18446744072077056912  NOTICE: GL_VERSION = OpenGL ES 3.1
22:47:10 T:18446744072077056912  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.10
22:47:10 T:18446744072077056912  NOTICE: GL_EXTENSIONS = GL_EXT_debug_marker GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth24 GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_EXT_read_format_bgra GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_required_internalformat GL_OES_vertex_array_object GL_OES_mapbuffer GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_type_2_10_10_10_REV GL_OES_fbo_render_mipmap GL_OES_element_index_uint GL_EXT_shadow_samplers GL_OES_texture_compression_astc GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_KHR_debug GL_EXT_occlusion_query_boolean GL_EXT_disjoint_timer_query GL_EXT_blend_minmax GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_OES_texture_3D GL_EXT_texture_storage GL_EXT_multisampled_render_to_texture GL_OES_surfaceless_context GL_OES_texture_stencil8 GL_EXT_shader_pixel_local_storage GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_ARM_mali_program_binary GL_EXT_sRGB GL_EXT_sRGB_write_control GL_EXT_texture_sRGB_decode GL_KHR_blend_equation_advanced GL_OES_texture_storage_multisample_2d_array GL_OES_shader_image_atomic
22:47:28 T:18446744072077056912   ERROR: Unable to activate the previous window
22:47:56 T:18446744072049179536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name servertools
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/default.py", line 28, in <module>
                                                launcher.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 59, in run
                                                from platformcode import xbmctools
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/platformcode/xbmctools.py", line 16, in <module>
                                                from servers import servertools
                                            ImportError: cannot import name servertools
                                            -->End of Python script error report<--
22:47:57 T:18446744072077056912   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.streamondemand/
22:47:57 T:18446744072077056912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/) failed
22:48:02 T:18446744072049179536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name servertools
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/default.py", line 28, in <module>
                                                launcher.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 59, in run
                                                from platformcode import xbmctools
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/platformcode/xbmctools.py", line 16, in <module>
                                                from servers import servertools
                                            ImportError: cannot import name servertools
                                            -->End of Python script error report<--
22:48:02 T:18446744072077056912   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.streamondemand/
22:48:02 T:18446744072077056912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/) failed
22:48:07 T:18446744072051485584   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name servertools
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/default.py", line 28, in <module>
                                                launcher.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 59, in run
                                                from platformcode import xbmctools
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.streamondemand/platformcode/xbmctools.py", line 16, in <module>
                                                from servers import servertools
                                            ImportError: cannot import name servertools
                                            -->End of Python script error report<--
22:48:07 T:18446744072077056912   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.streamondemand/
22:48:07 T:18446744072077056912   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/) failed
**********

**Comment by costaplus** [comment]
Ciao... mancano dei file essenziali per il funzionamento dell'addons, ti consiglio di eliminarlo e reinstallarlo... qualcosa non è andato a buon fine...

**Comment by alex78red** [comment]
Fatto è adesso funziona perfettamente. Grazie mille per l'aiuto!
