### ISSUE TITLE
New channel ed ajax

### ISSUE THREAD

**Issue by Bonobomagno** [streamondemand/plugin.video.streamondemand#225]
Salve a tutti,
Volevo aggiungere un sito di streaming anime  (animehdita.org). 
Come si gestiscono le chiamate ajax? Dovrebbero bastare delle richieste in post, 
visto che non c'è modo di avere le "pagine successive" in get. 
Nella core ho visto che sono presenti le api per le post, ma ci sono canali che già lo implementano?
Farei molto prima, visto che è da qualche ora che ci ho messo mano.
Voi che consigliate?

Comunque ci sta una wiki sulle librerie comuni? Documentazione insomma, si trova?

Un saluto ragazzi

**Comment by costaplus** [comment]
Ciao, 
ma hai già una bozza di canale preparato ?

**Comment by Bonobomagno** [comment]
Ho un po' rimaneggiato con il copy_past cambiando quello che serviva. Un paio di orette mi ci vogliono per i vari tag.
ho visto che un paio di server sono gestiti con richieste XMLHttpRequest (bc)
vediamo se nel weekend posso lavorarci. da come viene presentata su quel file là, pare semplice.

L'unica fatica è il testing, come lo fate voi? Come si eseguono in shell questi file? O lo installate direttamente?

**Comment by MrTruth0** [comment]
Per il testing io avvio Kodi attivo i log di kodi e di SOD e inizio a testare tutte le funzioni che ho aggiunto al canale, se qualcosa non va importo xbmc e utilizzo xbmc.log("text") per i vari log così da vedere come si comporta lo script.

**Comment by Bonobomagno** [comment]
Faticosamente tedioso testare così :/

Ho usato advanced rest client per ricostruire le richieste e funziona (risposta json)
Essenzialmente si passa una 15ina di variabili, ma solo 3 contano. Essendo un json in risposta, si leggono veloci (response.content e cerco gli href), ora resta la costruzione della domanda

resto aperto a dritte, probabilmente prima di settimana prossima non ci metterò mano

**Comment by BastAldo** [comment]
forse e' piu' semplice lavorare sulla sitemap :P

**Comment by Bonobomagno** [comment]
Non ci pensavo o.o
Però non si possono esplorare le categorie :/ 
Ma i post ci stanno!   Come alternativa alla home va bene, però il resto serve la chiamata post..
