### ISSUE TITLE
Problema Openload

### ISSUE THREAD

**Issue by Elvitek** [streamondemand/plugin.video.streamondemand#228]
Salve ragazzi, ci sono di nuovo i soliti problemi con la visualizzazione e il download da Openload. Spero presto in un vostro fix, grazie e buona serata.

**Comment by Elvitek** [comment]
P.S. Ho notato che c'è un problema anche con la visualizzazione tramite Akastream.

**Comment by lukaarma** [comment]
Ho aperto un issue uguale alla tua, quindi è un problema comune che openload dia problemi?

**Comment by lukaarma** [comment]
Chiudo l'altra issue e carico qui il mio log, ho gli stessi identici problemi che hai tu.

[kodi-log.txt](https://github.com/streamondemand/plugin.video.streamondemand/files/949269/kodi-log.txt)

**Comment by Elvitek** [comment]
Si si, ogni 5/6 giorni da problemi. Ora non sono esperto di queste cose ma credo che proprio il sito Openload cambia qualche url o altro e quindi loro di SoD devono far uscire il fix altrimenti non funziona più. Tanto bello Openload ma tanto palloso allo stesso tempo.

**Comment by dentaku65** [comment]
E' un problema periodico legato ad openload che cambia gli encode dei link; quando si ha del tempo si cerca di risolverlo decodificandoli; per qualche tempo (breve) funziona, poi gli owner ricambiano gli encode e tutto inizia da capo. Per piacere non aprite issue su openload visto che appunto cambia spesso.
