### ISSUE TITLE
Problema info scraper 

### ISSUE THREAD

**Issue by riccardovidotto** [streamondemand/plugin.video.streamondemand#237]
Ciao a tutti, qualcuno di voi utilizza le librerie per catalogare film e serie tv? Perchè sia impostando la lingua italiana che quella inglese sugli scraper (TVTB e TMDB) le informazioni compaiono in spagnolo. Utilizzo kodi 17.1 su ubuntu. Qualche idea su come risolvere?

**Comment by dentaku65** [comment]
Ciao @riccardovidotto non mi risulta; gli info scraper in SOD sono in italiano o vuote (vuote nel senso che la trama in italiano non è ancora disponibile in TVDB o TMDB), Puoi indicare un esempio, canale+serie?

**Comment by riccardovidotto** [comment]
Ciao @dentaku65, per esempio la serie "Game of Thrones" e il canale "PirateStreaming". Ma se sono vuote per l'italiano e imposto la lingua inglese, non dovrei vederle comunque in inglese?

**Comment by dentaku65** [comment]
@riccardovidotto no lo scraping di SOD funziona solo con l'italiano, nel senso che sono settate le API di TVDB per le info in italiano, le API di TVDB non hanno ancora implementato il fall-back su un'altra lingua al momento.

**Comment by riccardovidotto** [comment]
@dentaku65 e allora come fa a prendere automaticamente lo spagnolo? Comunque adesso, cambiando canale e reinstallando TMDB ottengo le informazioni in inglese, è già un passo avanti.

**Comment by dentaku65** [comment]
@riccardovidotto non saprei; uso osmc e kodi in inglese, ma sod mi passa le info dei plot in italiano; provando una serie tipo mr rob0t dal canale italia-film aggiungendola alla library, ii plot, appunto, sono in italiano. Non riesco a riprodurre il tuo problema.

**Comment by dentaku65** [comment]
@riccardovidotto forse intendevi la library relativamente ai plugin metadata?
