### ISSUE TITLE
file download : file cancellati 

### ISSUE THREAD

**Issue by angelof61** [streamondemand/plugin.video.streamondemand#241]
Buongiorno, 
ho un problema relativo al download dei file : 
- seleziono un contenuto qualsiasi
- faccio partire il download 
- vedo che il file si incrementa (in una finestra da Explorer)
- a download terminato, i file non c'è piu (cancellato) 

La versione di Kodi che uso è la v.16. mentre l'add on e la 5.5.1
Mille grazie per un aiuto.
Angelo

**Comment by dentaku65** [comment]
@angelof61 SOD è compatibile Kodi 17.1 e con quel ciclo di sviluppo; per le versioni precedenti non c'e' alcuna garanzia sulle funzionalità complete dell'addon, nè abbiamo le risorse per poter intervenire. Ti consiglio di o aggiornare Kodi o, se il tuo device non lo supporta, di utilizzare un device compatibile con Kodi 17.1

**Comment by angelof61** [comment]
buongiorno!
ho aggiornato alla versione 17.1
ho riprovato a fare il download del file e lo vedo nella cartella.
Man mano che il download prosegue riesco a vedere che si incrementa.
Una volta terminato il download il file non c'è piu. Il comportamento è
esattamente come per la versione 16
Grazie mille per un suggerimento o un aiuto
Angelo


Il giorno 6 maggio 2017 11:37, dentaku65 <notifications@github.com> ha
scritto:
