### ISSUE TITLE
Richiesta e domanda

### ISSUE THREAD

**Issue by Elvitek** [streamondemand/plugin.video.streamondemand#247]
Salve ragazzi, scusatemi se ho aperto un "issue" ma non sapevo dove altro chiedervi queste cose e spero mi possiate rispondermi ugualmente. Detto questo, la mia richiesta è questa: Non so se è possibile ma nella modalità "download", potete introdurre il download in background? Quando si scarica qualcosa, bisogna soltanto rimanere in quella schermata del download aspettando che finisce ma sarebbe molto comodo scaricare un film o una serie tv mentre si guarda qualcosa già scaricato senza usare app explorer esterne per avviarle da " fuori" e spero si possa fare.

Mentre la domanda è questa: Quando aggiorno SoD aggiungendo i fix, scarico sia i fix che i "merge" installandoli tutti insieme uno dopo l'altro. Faccio bene a fare in questo modo o posso anche installare soltanto i "merge" ? 

Grazie ancora e scusatemi per il finto "issue".

**Comment by costaplus** [comment]
Ciao Evil, 
non sei il primo che propone il dowload in background tantè che kodilive tv ha creato una versione modificata di SoD!
Ma ti chiedo, se sto vedendo un film preferirei vederlo senza rallettamenti che un download di mezzo può generare giusto ?? 
Ora se i download li lasci in attesa nell'elenco e mentre fai altro li avvii tutti insieme non va bene ?
Inoltre nella maggior parte dei casi chi utilizza SoD lo utilizza soprattutto per lo streaming quindi avere dei download che occupano banda sarebbe deleterio per la qualità inoltre mi chiedo perchè fare il download se poi non hanno una qualità eccellette! A questo punto scaricherei torrent!
Inoltra devi anche pensare che SoD viene usato da tanti tipi di device con potenze ridotte ed è per questo che si cerca di avere una linea comu e per non dare problemi su nessuno di questi, Poi ovviamente ogniuno è libero di pensarla come crede.
Per i fix sarebbe meglio e lo dico per te, che tu aspettassi l'aggiornamento automatico piuttosto che quello manuale per 3 motivi:
1 la versione pubblicata zip è l' ultima funzionante.
2 i canali si aggiornano automaticamente.
3 il resto viene condiviso da noi che spesso è lasciato a metà perchè usiamo il git anche come mezzo di condivisione.
 Quindi fai pure a tuo rischio a pericolo.

Ciao.

Costaplus
