### ISSUE TITLE
[Feature request] Recently watched history

### ISSUE THREAD

**Issue by mlessio** [streamondemand/plugin.video.streamondemand#256]
This is just a feature request, feel free to discard it.

It would be nice to have a "Recently watched" history to quickly come back(e.g. to a tv show i started watching, and i forgot to add to my favourites).

**Comment by dentaku65** [comment]
A sort of this feature is already present in the Library function; as soon as you watch an episode in the library that episode will be marked as checkmark

**Comment by mlessio** [comment]
The library shows only the things i have added to library. I was meaning some way to automate the process.

**Comment by dentaku65** [comment]
To have such entry in the menu (example "Recently Watched") we have to modify all channels... not an option at the moment
