### ISSUE TITLE
[Richiesta]

### ISSUE THREAD

**Issue by Tnebi** [streamondemand/plugin.video.streamondemand#257]
E' possibile aggiungere il sito ilgeniodellostreaming.cc nei siti in cui effettua la ricerca l'addon? Contiene ottimi contenuti e spesso sono hostati su openload soltanto.

**Comment by dentaku65** [comment]
Il canale è già presente 
https://raw.githubusercontent.com/streamondemand/plugin.video.streamondemand/master/channels/ilgeniodellostreaming.py

**Comment by Tnebi** [comment]
Ma non credo funzioni correttamente. Se cerco un titolo specifico presente sul sito non risulta in ricerca

**Comment by dentaku65** [comment]
La ricerca funziona sia nel canale che nei risultati globali; cercato "dance again" e lo trova in entrambi i contesti
