### ISSUE TITLE
Problema Flashx

### ISSUE THREAD

**Issue by mattitotti** [streamondemand/plugin.video.streamondemand#265]
Ragazzi Potete Fixare Flashx? Sempre il solito errore.

**Comment by dentaku65** [comment]
Chiudo questa richiesta. Non è specificato un log, un canale, un link e nemmeno un esempio

**Comment by mattitotti** [comment]
su majintoon qualsiasi link di flashx  dice che si è verificato un errore con il connettore Flashx
