### ISSUE TITLE
Problema flashx

### ISSUE THREAD

**Issue by mattitotti** [streamondemand/plugin.video.streamondemand#266]
Ragazzi scusatemi se non mi sono espresso bene flashx non funziona...andate su majintoon,qualsiasi link di flashx che avvierete dice che si è verificato un errore con il connettore video 
![screenshot 2](https://cloud.githubusercontent.com/assets/28977629/26495213/f927fc76-4222-11e7-8605-be1ea9a48d2a.png)

**Comment by MrTruth0** [comment]
Questo problema non dipende da noi, flashx è down in questi gioni, non so quando tornerà on. https://www.flashx.tv/
