### ISSUE TITLE
Dreamsub add to library not working

### ISSUE THREAD

**Issue by dentaku65** [streamondemand/plugin.video.streamondemand#268]
L'aggiunta delle serie (e probabilmente il download) non funziona in Dreamsub; l'errore dice che non è possibile trovare gli episodi; se non si riesce a sistemare si puo' rimuovere la funzione

**Comment by princeHago** [comment]
Aggiungo che anche il canale di AnimeForce da lo stesso problema.

**Comment by Squalo08** [comment]
Non solo questi 2, ma in tutti i principali canali anime non funziona l'aggiunta alla libreria, l'errore dice che non è possibile trovare gli episodi,anche se ci sono e si riescono a vedere
