### ISSUE TITLE
Serie TV CB01

### ISSUE THREAD

**Issue by realealessio** [streamondemand/plugin.video.streamondemand#277]
Nella ricerca di serie tv in cineblog01 i risultati vengono visualizzati ma nel momento in cui si clicca sul nome della serie tv questa carica all'infinito senza mostrare gli episodi e dopo qualche minuto manda in crash anche kodi. Provato su kodi 17.3 sia su Windows che su Libreelec con lo stesso risultato. Non so da cosa possa dipendere visto che con i film questo non accade.

**Comment by MrTruth0** [comment]
Ho appena testato su Win 10 con kodi 17.3, nessun problema ... log ?

**Comment by realealessio** [comment]
Scusami ho dimenticato di postare il log. eccolo [qui.](https://pastebin.com/raw/YbJ21vEy).
Ho riprovato ma a me non va proprio.

**Comment by MrTruth0** [comment]
Hai provato a reinstallare SOD ?

**Comment by realealessio** [comment]
Io come media center uso solamente un Raspberry Pi3 con Libreelec dove anche li ho l'errore. Ieri sera per constatare se era un problema circoscritto ho installato kodi e streamondemand sul mio pc con win 10 da dove ho mandato il log e mi da lo stesso errore. Quindi possiamo dire che già da un'installazione pulita si presenta l'errore.

**Comment by errmax** [comment]
Confermo.
Il problema e' dovuto al cambiamento della struttura della pagina delle serie su cb01

file: plugin.video.streamondemand/channels/cineblog01.py
line: 362
        patron = '((?:.*?<a href=".*?"[^=]+="_blank">.*?<\/a>)+)'

Senza essere un esperto cambiando questa linea in

        patron = '((?:.*?<a href=".*?".*target="_blank".*>.*?<\/a>)+)'

tutto funziona

**Comment by realealessio** [comment]
Confermo! Applicando la modifica funziona tutto come deve. Grazie a @errmax per il supporto. Ho provato a controllare anche io il codice del canale ma non ero riuscito a scovare l'errore. 
Si può chiudere.
