### ISSUE TITLE
Problemi con il download

### ISSUE THREAD

**Issue by lukaarma** [streamondemand/plugin.video.streamondemand#280]
Qualsiasi film/serie tv io cerchi di scaricare da qualsiasi provider disponibile, Kodi inizializza il download e poi si blocca allo 0% senza scaricare nulla.
Ho provato a fare una installazione pulita sia del plugin che di kodi stesso senza risultato.
Log: https://pastebin.com/h6eFr6UP

**Comment by MrTruth0** [comment]
Ho provato con vari server e il download a me parte, con kodi 17.3 prova ad aggiornare.

**Comment by lukaarma** [comment]
ok provo

**Comment by lukaarma** [comment]
non ha risolto il problema...

**Comment by lukaarma** [comment]
il problema persiste identico anche facendo una clean install di kodi 17.3

**Comment by MrTruth0** [comment]
Quando hai fatto l'installazione pulita hai controllato che non sia rimasta la cartella di kodi in AppData ?

**Comment by lukaarma** [comment]
Sisi, durante la disinstallazione ho cancellato anche la cartella in AppData

**Comment by costaplus** [comment]
Che percorso usi per i download ??
Hai provato ad avviare kodi da amministratore!

**Comment by lukaarma** [comment]
uso un percorso personalizzato di solito ma ora stavo facendo i test con quello di default.
ora provo con amministratore

**Comment by lukaarma** [comment]
ok continua a non funzionare :(

**Comment by dentaku65** [comment]
Il download verrà rimosso
