### ISSUE TITLE
Problemino (forse) con la versione 5.5.6

### ISSUE THREAD

**Issue by marco-shagrat** [streamondemand/plugin.video.streamondemand#299]
Giusto una informazione da ignorante, fino alla versione 5.5.5 quando clickavo su un film oltre alle varie opzioni di riproduzione trovavo anche un comodissimo (a mio parere ovviamente) bottone "download".

Non lo trovo più.

E' stato tolto? sostituito con altro? disabilitato?

Grazie per l'attenzione

**Comment by MrTruth0** [comment]
Ci dispiace, la funzione per i download è stata rimossa per motivi legali.
