### ISSUE TITLE
Ricerca not working

### ISSUE THREAD

**Issue by iz8mbw** [streamondemand/plugin.video.streamondemand#30]
Ciao.
La ricerca sembra che dopo aver restituito il contenuto nei vari canali/siti dopo la selezione del canale/sito l'elenco è vuoto.
Esempio:
1. Ricerca globale
2. Cerca nei canali
3. Nuova ricerca film

la ricerca trova i risultati sui vari canali ma quando si seleziona/sceglie il canali l'elenco all'interno è vuoto (mostra solo i due punti ".." per salire di livello).

Grazie

**Comment by Dr-Zer0** [comment]
Ciao,
puoi indicare nell'esempio che stringa hai ricercato e quale canale ha dato la ricerca vuota?

**Comment by iz8mbw** [comment]
Ciao.
Prova a cercare "shrek" e vedrai che usciranno i risultati anche su dei canali che dopo averli selezionati non restituisco link.
I canali che non restituisco risultati per esempio sono i primi due in lista e alcuni successivi.
Fammi sapere se le info sono sufficienti o se necessiti di sapere proprio su quali canali non ci sono i link.
Grazie per l'effort.

**Comment by dentaku65** [comment]
Non mi risulta. La ricerca funziona correttamente. Prova ad installare da zero la versione 5.3.9
