### ISSUE TITLE
Remove old code from channels

### ISSUE THREAD

**Issue by SeiTaN** [streamondemand/plugin.video.streamondemand#300]
Hi,

First of all, I hope you don't mind if I write here.

When we create a channel we usually copy from other as template, unfornatelly when we use old channels we drag old code too.

Here is code you don't need anymore since the addon changed, and we already changed it in pelisalacarta.

```python
__channel__ = "altadefinizione01"
__category__ = "F,S"
__type__ = "generic"
__title__ = "AltaDefinizione01"
__language__ = "IT"

host = "http://www.altadefinizione01.onl"

headers = [
    ['User-Agent', 'Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0'],
    ['Accept-Encoding', 'gzip, deflate'],
    ['Referer', host]
]

DEBUG = config.get_setting("debug")


def isGeneric():
    return True

def mainlist(item):
    logger.info("streamondemand.altadefinizione01 mainlist")

```

- constant vars, like `category, type, title` or `language` you don't need it anymore, addon get them from .xml file, you may even change `__channel__` var for a string.

- method `isGeneric` is orphan and it isn't call from anywhere, so it can remove too.

- `DEBUG` var logic is also inside logger.py file, you can use `logger.debug` method instead _if and logger.info_ syntaxis.

- use `httptools.downlopage` instead of `scrapertools` method to download page from url, it integrates anti-cloudflare method, it's faster and cleaner.

- `headers` var, at 99% of the time, you don't need to declarate it, httptools has its own headers.

- breadcrumps in method `logger.info()` it's done automatically, as I saw it's fine in other parts of streamondemand, and it will be cleaner and clear it is done too in channels you can check it in log files.

Ciao.

**Comment by dentaku65** [comment]
@SeiTaN thanks for the tip and explanation!

**Comment by dentaku65** [comment]
I've update a channel based on your indication https://github.com/streamondemand/plugin.video.streamondemand/commit/ed623904fa8e7a39579896c32bf6140630c75af9 it is a simple one; but tried one more complicated and I got some errors, especially the ones with episodes... I'll check later

**Comment by SeiTaN** [comment]
@dentaku65 what channel and errors?

**Comment by dentaku65** [comment]
Sorry my fault. The channel was this one https://github.com/streamondemand/plugin.video.streamondemand/commit/cb503e8163558319cb2cfaaa24c93adbf4898c22 Anyway I really don't see that httptool.download is faster, perhaps I did something incorrect or simply is my perception... talking about test on RPI2...

**Comment by SeiTaN** [comment]
if you want debug log
```python
if DEBUG: logger.info(
 -            "title=[" + scrapedtitle + "], url=[" + scrapedurl + "], thumbnail=[" + scrapedthumbnail + "]")
```
for 
```python
logger.debug("title=[" + scrapedtitle + "], url=[" + scrapedurl + "], thumbnail=[" + scrapedthumbnail + "]")
```

About httptools speed, in our test it always was faster, but in some pages the differences weren't so great.  I mean measuring elapsed time.
