### ISSUE TITLE
wanted login debriders

### ISSUE THREAD

**Issue by SiNaPsEr0x** [streamondemand/plugin.video.streamondemand#308]
why remove the login of real-debrid? in the option of plugin on login tab it's erased login ... :( fix it

**Comment by dentaku65** [comment]
I premium sono stati disabilitati sul nuovo Pelis e quindi anche qui
https://github.com/streamondemand/plugin.video.streamondemand/blob/master/resources/settings.xml
Puoi scommentare e vedere se funziona

**Comment by SiNaPsEr0x** [comment]
ma come mai si puo sapere?
