### ISSUE TITLE
Come aggiungere un sito personalizzato... vorrei provare ad aggiungere tvshow.me

### ISSUE THREAD

**Issue by DjDiabolik** [streamondemand/plugin.video.streamondemand#31]
Fino a qualche giorno fà.......... riuscivo a indirizzare i risultati del sito usando Release HUB. Da un paio di giorni invece i risultati delle ricerche appaiono vuoti mentre il sito da PC sembra funzionare ma hanno, sembra, inserito una pagina di SPAM (che apre link a siti inutili) prima che i link dei vari programmi diventino cliccabili.

A questo punto mi chiedo......... come funziona la modalità per aggiungere un sito personalizzato ?? Il sito in questione cosa deve avere ?

So che il sito non è italiano......però appunto se è possibile vorrei aggiungerlo da me.............

**Comment by costaplus** [comment]
Ciao,
prova a leggerti questo:
http://www.mimediacenter.info/foro/viewtopic.php?f=38&t=7913

**Comment by DjDiabolik** [comment]
Proverò a darci una vista......... ma dalle opzioni interne ci sono già dei slot vuoti... eventualmente com'è che funzionano quelli ?

**Comment by costaplus** [comment]
Non esistono slot vuoti, i canali vengono letti a runtime quindi più ne aggiungi più ne vedi !!!

**Comment by DjDiabolik** [comment]
Sicuro ? Nelle impostazioni......... vai nel tab "Login" e scorri in basso. Ad un certo punto trovi tanti slot.... alla fine trovi diversi slot che dicono "Enable personal channel".
Pensavo che li si potesse aggiungere nuovi siti appunto............. 

Ma se cosi non è appunto, e partendo dal fatto che non conosco affatto il phyton, dici che è impossibile appunto che io potessi fare qualcosa ?
Cioè se ho capito bene in pratica io è un nuovo scrapers che dovrei andare a fare giusto ? E se si poi andarlo ad aggiungerlo a quelli già presenti sull'attuale versione (ma cosi facendo poi nel momento che una nuova versione viene rilasciata il file viene sovrascritto oppure viene aggiornato ad ogni riavvio del kodi quindi perdo eventuali modifiche ogni volta?) ? Non mi sembra poi cosi semplice......

**Comment by DjDiabolik** [comment]
Cmq sia mi sono registrato anche sul forum......... poi casomai ci posso creare a creare un chan da me.... sperando che non sia un casino
