### ISSUE TITLE
Problema con animestream

### ISSUE THREAD

**Issue by luX0r-reload** [streamondemand/plugin.video.streamondemand#316]
Ciao,
in SoD versione 5.5.8 installata due giorni fa, quando seleziono il canale animestream mi esce un messaggio che dice "qualcosa è cambiato nel sito, etc".

edit: provata una vecchia SoD versione 5.5.6 e tutto funziona correttamente.
Se può essere utile l'errore che scrive la 5.5.8 nel log si riferisce al file animestream.py, funzione GetDirectory e parla di errore nel blocco di indentazione. Linea 302

**Comment by costaplus** [comment]
Grazie per la segnalazione(fossero tutte così) lo sistemo.

Costaplus

**Comment by costaplus** [comment]
Fixato!

**Comment by luX0r-reload** [comment]
Grazie mille!

**Comment by msagliocco** [comment]
@costaplus stesso identico problema ma per tanti altri canali. Da cb01 a altadef a prescindere dall host.
Di fatto con la 5.8 non mi funziona più niente

**Comment by costaplus** [comment]
Hai provato a eliminare addon e reinstallarlo ?

**Comment by costaplus** [comment]
Elimina anche la cartella in userdata

**Comment by msagliocco** [comment]
Sono su Android tv, è un po' complicato ma ci provo

**Comment by msagliocco** [comment]
Disinstallato e reinstallato ultima release 5.8 e ora, anche se in partenza da un errore, poi funziona.
Ho letto ora della chiusura: grazie ragazzi per tutto quello che avete fatto! 🤘
