### ISSUE TITLE
remote_server_url for updates

### ISSUE THREAD

**Issue by velvet1976** [streamondemand/plugin.video.streamondemand#320]
Other issue found about updater module:

    16:02:48.989 T:1501557664   ERROR: ######## ERROR #########
    16:02:48.989 T:1501557664   ERROR:     [streamondemand.core.servertools.get_server_parameters] Error al cargar el servidor: version
                                                Traceback (most recent call last):
                                                  File "/storage/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 495, in get_serv$
                                                    JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
                                                KeyError: 'server'
    16:02:49.167 T:1501557664   ERROR: Exception in thread Thread-252:
                                                Traceback (most recent call last):
                                                  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                  File "/usr/lib/python2.7/threading.py", line 754, in run
                                                  File "/storage/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 234, in update_server
                                                    remote_server_url, remote_version_url = servertools.get_server_remote_url(server_name)
                                                  File "/storage/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 812, in get_serv$
                                                    remote_server_url = server_parameters["update_url"] + server_name + ".py"
                                                KeyError: 'update_url'

**Comment by velvet1976** [comment]
More details about the environment.
Running on Raspberry PI 3 with plugin version 5.5.8:

    16:01:34.267 T:1962004480  NOTICE: Starting Kodi (17.3 Git:147cec4). Platform: Linux ARM 32-bit
    16:01:34.267 T:1962004480  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
    16:01:34.267 T:1962004480  NOTICE: Kodi compiled May 25 2017 by GCC 6.2.0 for Linux ARM 32-bit version 4.9.29 (264477)
    16:01:34.267 T:1962004480  NOTICE: Running on LibreELEC (official) - Version: 8.0.2, kernel: Linux ARM 32-bit version 4.9.29
    
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <addon id="plugin.video.streamondemand"
           name="Stream On Demand"
           version="5.5.8"
           provider-name="iSOD Crew">
      <requires>
        <import addon="xbmc.python" version="2.1.0"/>
        <import addon="script.module.libtorrent" optional="true"/>
      </requires>
      <extension point="xbmc.python.pluginsource" library="default.py">
        <provides>video</provides>
      </extension>
        <extension point="xbmc.addon.metadata">
            <summary lang="it">SOD Media</summary>
            <description lang="it">SOD Media</description>
            <summary lang="en">SOD Media</summary>
            <description lang="en">SOD Media</description>
            <platform>all</platform>
            <license>GNU GPL v3</license>
            <forum>http://www.mimediacenter.info/foro/viewforum.php?f=36</forum>
            <source>https://github.com/streamondemand/plugin.video.streamondemand</source>
        </extension>
        <extension point="xbmc.service" library="library_service.py" start="login|startup">
        </extension>
    </addon>

**Comment by frakbe** [comment]
Hi, I've had the same problem.
To solve:

- Uninstall streamondemand plugin from kodi
- Exit from kodi interface
- Delete the plugin.video.streamondemand directory located on ~/.kodi/userdata/addon_data
- Run Kodi and reinstall streamondemand package

Bye
