### ISSUE TITLE
Non so se avete notato quindi segnalo anche qua... anche se non dovrebbe esser grave..... osmc errore all'avvio su diversi RPi.

### ISSUE THREAD

**Issue by DjDiabolik** [streamondemand/plugin.video.streamondemand#322]
Da circa 5 o 6 giorni all'avvio di OSMC su Pi2 nel log spunta fuori questo:
`19:46:01.076 T:1464857584   ERROR: ######## ERROR #########
19:46:01.076 T:1464857584   ERROR:     [streamondemand.core.servertools.get_server_parameters] Error al cargar el servidor: version
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 495, in get_server_parameters
                                                JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
                                            KeyError: 'server'`

Qualcuno riporta che la stessa cosa è spuntata fuori anche su Pi3 con SOD 5.5.8........  credo che la cosa sia relativo a qualcosa a che fare con i server ma la cosa non sembra interessare la procedura di aggiornamento all'avvio di quest'ultimi perchè se si lancia/forza l'aggiornamento di questi lo stesso errore non compare nel log una seconda volta.......

**Comment by dentaku65** [comment]
In OSMC 
sudo apt-get install python-xmltodict

**Comment by DjDiabolik** [comment]
Sto installando.... devo poi riavviare OSMC per vedere se l'errore scompare......

Nelle versioni successive questo xmltodict potrebbe essere incluso ?

**Comment by DjDiabolik** [comment]
@dentaku65 ciao.. allora ti segnalo che ho installato l'xmltodict ma lo stesso errore rimane.
Compare nel log anche se lancio manualmente l'aggiornamento della lista canali/server:
Tra le altre cose compare anche un'altro errore poco dopo ma non credo sia rilevante... io cmq ti riposto tutto:
`14:27:44.757 T:1442837488   ERROR: ######## ERROR #########
14:27:44.757 T:1442837488   ERROR:     [streamondemand.core.servertools.get_server_parameters] Error al cargar el servidor: version
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 495, in get_server_parameters
                                                JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
                                            KeyError: 'server'
14:27:48.642 T:1959055360   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?ewogICAgImFjdGlvbiI6ICJ1cGRhdGVfZnJvbV9tZW51IiwgCiAgICAiY2F0ZWdvcnkiOiAiIiwgCiAgICAiY2hhbm5lbCI6ICJ1cGRhdGVfdmVyc2lvbiIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjoge30sIAogICAgInRodW1ibmFpbCI6ICIvaG9tZS9vc21jLy5rb2RpL2FkZG9ucy9wbHVnaW4udmlkZW8uc3RyZWFtb25kZW1hbmQvcmVzb3VyY2VzL2ltYWdlcy9tYWluX21lbnVfZG93bmxvYWQucG5nIiwgCiAgICAidGl0bGUiOiAiQWdnaW9ybmEgQ2FuYWxpL1NlcnZlciIsIAogICAgInRvdGFsSXRlbXMiOiAwLCAKICAgICJ2aWV3bW9kZSI6ICJtb3ZpZSIKfQ%3d%3d
14:27:48.645 T:1959055360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?ewogICAgImFjdGlvbiI6ICJ1cGRhdGVfZnJvbV9tZW51IiwgCiAgICAiY2F0ZWdvcnkiOiAiIiwgCiAgICAiY2hhbm5lbCI6ICJ1cGRhdGVfdmVyc2lvbiIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjoge30sIAogICAgInRodW1ibmFpbCI6ICIvaG9tZS9vc21jLy5rb2RpL2FkZG9ucy9wbHVnaW4udmlkZW8uc3RyZWFtb25kZW1hbmQvcmVzb3VyY2VzL2ltYWdlcy9tYWluX21lbnVfZG93bmxvYWQucG5nIiwgCiAgICAidGl0bGUiOiAiQWdnaW9ybmEgQ2FuYWxpL1NlcnZlciIsIAogICAgInRvdGFsSXRlbXMiOiAwLCAKICAgICJ2aWV3bW9kZSI6ICJtb3ZpZSIKfQ%3d%3d) failed`
Anche se sarebbe + chiaro mettere i TAG in modo che andasse a capo proprio come appare nel log.... spetta:
https://pastebin.com/Msc1UF9v

Qua non viene proprio rispettato però potrebbe essere + chiaro.......
