### ISSUE TITLE
Quale è l'ultima versione che permetteva di fare il download?

### ISSUE THREAD

**Issue by tmontanaro** [streamondemand/plugin.video.streamondemand#323]
Come mai è stata rimossa la funzione download e come mai continuate a non rimetterla neanche nei nuovi aggiornamenti! Era davvero molto utile quando si doveva viaggiare e non si aveva la connessione!!!

Quale è l'ultima versione che aveva la possibilità di fare il download?

**Comment by tmontanaro** [comment]
Rispondo da me: guardando i commit sembra che l'ultima versione che supporta il download è la 5.4.4
Purtroppo però questa versione non funziona con kodi 17.

Alternative per scaricare ciò che si sta guardando sono:
a) DreamCatcher
b) Offline wizard

Entrambi, però sembrano non funzionare con l'ultima versione di Kodi e streamondemand!

**Comment by jokerulez** [comment]
A questa pagina http://kodilive.eu/SOD-KLTV trovi una versione modificata
per consentire il download tramite kodi live tv che integra un buon
download manager

Il 07 ago 2017 3:24 PM, "Teodoro Montanaro" <notifications@github.com> ha
scritto:

**Comment by DjDiabolik** [comment]
Ma ha senso fare il download quando si usa il kodi ? Obbiettivamente se io uso devo usare il Kodi ad esempio su windows non ha + senso usare app P2P ? Su altri dispositivi kodi e lo stesso SOD sono a mio avviso comodi per via della fruibilità degli stessi streaming e in questo caso specifico se devo usare il SOD per scaricare un flusso di uno streaming è preferibile a mio avviso sempre utilizzare un software P2P per ottenere l'avi che spesso e volentieri è lo stesso che viene re-encodato (con alcuni casi evidenti perdite di qualità) in flv per lo stesso streaming.

**Comment by tmontanaro** [comment]
La soluzione SOD-KLTV è perfettamente funzionante! Grazie jokerulez!!! ;-)
