### ISSUE TITLE
compatibilità Plex

### ISSUE THREAD

**Issue by croccio** [streamondemand/plugin.video.streamondemand#327]
farete mai una versione per flex?

**Comment by costaplus** [comment]
Esiste già una versione per plex, mancherà di aggiornamento, ma c'è in giro per il forum.

**Comment by croccio** [comment]
ne ho trovato uno, ma non sembra funzionare, non mi trova niente. ecco quello che ho trovato io http://www.mimediacenter.info/foro/viewtopic.php?t=8049

**Comment by costaplus** [comment]
Si è proprio quello! Hai provato ad entrare nei canali ?
Purtroppi per provarlo dovrei installarmi plex server😆😆

**Comment by croccio** [comment]
Sì ho provato, ma non mostrano i link da dove è possibile vedere il film.

Il 11/ago/2017 19:42, "costaplus" <notifications@github.com> ha scritto:

**Comment by costaplus** [comment]
Quando avrò tempo gli darò un'occhio!
