### ISSUE TITLE
SoD aggiornamento

### ISSUE THREAD

**Issue by braguzz** [streamondemand/plugin.video.streamondemand#328]
Scusate la domanda forse sciocca, ma come fare per aggiornare? Devo farmi un mio fork e aggiornare a 'mano'? Grazie e scusate ancora.

**Comment by costaplus** [comment]
No! Ma cosa intendi aggiornare ??
Se hai voglia puoi anche collaborare, noi abbiamo sempre bisogno di aiuto!

**Comment by braguzz** [comment]
Quindi ci saranno nuove release qui?
A livello di programmazione sono molto molto mooto arrugginito... E con pyhton ... mai programmato

**Comment by SiNaPsEr0x** [comment]
ma perchè avete rimosso real-debrid?

**Comment by braguzz** [comment]
Quindi, scusate se insisto, le modifiche saranno oggetto di nuovi aggiornamenti, o preferite non rilasciarli? (Va aggiornato a mano??)

**Comment by costaplus** [comment]
Ma nessuno ha detto nulla!! se non ti abbiamo risposto ci sarà un perchè!

**Comment by SiNaPsEr0x** [comment]
Non capisco perché togliere delle feature che tantissimi invece usavano basta leggere il forum senza che esse portavano peggiorie ma che scelta del  cazzo

**Comment by braguzz** [comment]
Non capisco perché tu:
- offenda
- scriva sulla mia issue

Ps. Riguardo alla mia domanda sinceramente... Non ho capito... Bo?

**Comment by MrTruth0** [comment]
"Scelta del cazzo" ti pare che ci divertiamo a levare features ? Poi la gente ha i cazzi suoi a cui pensare, non tutti possono stare 24h dietro al progetto, noto che molti pensano che le cose si facciano con il solo schiocco delle dita ...

@braguzz Stiamo molto occupati in questo periodo, per gli aggiornameni puoi stare tranquillo perchè SOD fa da solo ad ogni avvio di kodi. Se lasci kodi sempre on, quando vedi delle modifiche (di canali o servers) su github vai nel menù di SOD e avvia l'aggiornamento dei canali/servers, così ricevi le ultime modifiche.

**Comment by SiNaPsEr0x** [comment]
La frase era riferita alla feature tolta per motivi non tecnici... dato che quel menù rimane comunque attivo non si spiega tecnicamente il perché della rimozione... ho provato a riattivarlo a mano ma dal solo file setting non si riattiva quindi credo  ci sia qualche altra cosa da toccare... se nn volete un progetto open nn state su github nn è questa la politica

**Comment by costaplus** [comment]
Scusa SiNaPsEr0x, noi di SoD non abbiamo mai obbligato nessuno a seguirci e accettiamo anche le critiche, ma ti ricordo che noi non siamo un'azienda e quello che facciamo lo facciamo solo per hobby e passione e non certo per accontentare chi ci segue.
Se sai come sistemarlo ti prego di farti un fork e sarai liberissimo di modificare il tuo fork come meglio  ti pare. Come già detto prima nessuno di noi ha mai usato un'account di quel tipo e non siamo abbligato a portarlo avanti, prova con la Pure Ita forse ha ancora qualcosa, oppure riparti da pelis!
Mi spiace, ma non mi sembra carino offenderci perchè a te la cosa non piace.

Costaplus

**Comment by SiNaPsEr0x** [comment]
No no per carità era solo capire come almeno riattivarlo... se riattivo nel settings.xml dei debrid non  basta... o almeno vedo dalla 5.4 cosa è cambiato e al massimo a chi interessa lo forko con i debrid attivati

**Comment by costaplus** [comment]
Ecco così va meglio!
Ovviamente visto che tu hai le credenziali debrid puoi aiutarci a sistemarlo e integrarlo nel progetto uffciale, ovviamente se tu lo vorrai... noi accettiamo sempre chi ci può aiutare.
Grazie.

**Comment by SiNaPsEr0x** [comment]
@costaplus mi devi perdonare per prima ma sono mesi che nessuno mi rispondeva e un po lo sfogo ci stava... odio 3000 fork ecco xche provavo da me prima in locale... allora si vi potrei aiutare fammi sapere come e in che modo con real-debrid ad esempio che è quello che (da quello che so) è quello piu usato in europa... in servers/debriders tecnicamente mi sembra tutto uguale alla 5.4 ma non capisco perchè decommentando le righe dalla 40 in giu del file plugin.video.streamondemand/resources/settings.xml e apparendomi il menu tutto ciò non funziona sulla selezione ad esempio del file.. magari voi che seguite il progetto da piu tempo riuscite meglio a sapere il perchè... ora provo con un un log dettagliato e capiremo il perchè

**Comment by SiNaPsEr0x** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=8471

comunque nemmeno attivando nel file settings.xml real-debrid (nonostante sia il flag su active tutto ciò funziona... credo che lo script in python forse non vada bene... ecco xche chiedevo aiuto
