### ISSUE TITLE
debriders rimossi?!?!?!

### ISSUE THREAD

**Issue by SiNaPsEr0x** [streamondemand/plugin.video.streamondemand#329]
uno non vuole criticare ma perchè è stata rimossa la funzione migliore da SOD? dove son finiti i debriders?

**Comment by DjDiabolik** [comment]
I che ? Scusa ma cosa dovrebbero essere ? Magari li ho sempre usati senza saperlo oppure è una cosa utile che non ho mai usato.........

**Comment by SiNaPsEr0x** [comment]
per sbloccare l'HD degli hoster usa real-debrid.com è un sito che ti sblocca tutti i premium.. dubito li hai usati perchè vanno usati manualmente.. dentro SOD c'era la configurazione e andavo tutto in full HD ora non piu

**Comment by costaplus** [comment]
purtropppo nessuno di noi li ha mai usati e molti lamentavano il malfunzionamento. Non avendoli mai usati sono state tolte le impostazioni, forse è rimasto altro... ma ripento nessuno di noi li ha mai usati....
Mi spiace!!

**Comment by SiNaPsEr0x** [comment]
Riattivandoli dal file setting si attiva il menù ma nella selezione del file apre solo l hosting e nn il debrider link... c'è qualche altra modifica che si deve fare?

**Comment by DjDiabolik** [comment]
mmmmmmm... in effetti ci dovevo arrivare... debriders :)

**Comment by kaimano** [comment]
Per favore reinserite i debriders!!!!

**Comment by SiNaPsEr0x** [comment]
@kaimano sono mesi che li chiedo... ma secondo me non sanno piu come fare.. da quando lo staff principale è andato via...

**Comment by MrTruth0** [comment]
Staff principale ? Siamo sempre gli stessi ..

**Comment by DjDiabolik** [comment]
Mi sa che parla dei developers direttamente del Pelislacarta che hanno, x ora, abbandonato il progetto per passare forse al Covenant giusto ?

**Comment by costaplus** [comment]
fine del supporto!
