### ISSUE TITLE
Altadefinizione01 - Offline o cambio di host ?

### ISSUE THREAD

**Issue by DjDiabolik** [streamondemand/plugin.video.streamondemand#332]
http://www.altadefinizione01.onl/

Sembra essere questo il sito giusto ? Si apre una pagina di Apache2 debian....... qualcosa è saltato o semplice cambio di host ?
Una semplice ricerca di Google riporta a diversi altri mirrors tipo .love . oltre ma non vorrei fossero tutti siti doppioni o semplici copie del "vero" AltaDefinizione01.......

P.S. Magari questa non è la sede adatta per queste segnalazioni o richieste ma, sono andato a vedere, e apparentemente il mio IP e non il mio nickname (sembra) risulta bannato sulla board principale del pelislacarta...........

**Comment by As3ro** [comment]
Fixato con la 5.6.0

**Comment by DjDiabolik** [comment]
Si... il sito sembra anche tornato up.... posso close and comment 👍
