### ISSUE TITLE
shared favourites does not work: fix proposed

### ISSUE THREAD

**Issue by clamel77** [streamondemand/plugin.video.streamondemand#337]
Hello,
I'm an enthusiast user.
My goal was to save kodi favourites on shared samba server. I used pathsubstitution in advancedsettings.xml.

```
<pathsubstitution>
 <substitute>
   <from>special://profile/favourites.xml</from>
   <to>smb://192.168.1.103/kodi/userdata/favourites.xml</to>
 </substitute>
</pathsubstitution>

```

It works fine in kodi.

When I try to add a favourite after a SOD global search, I noticed the preferred is saved into localfile favourites and not into remote file.

I found the problem shoud be in .kodi/addons/plugin.video.streamondemand/channels/favoritos.py file, in  this section

```
try:
    # Fijamos la ruta a favourites.xml
    if config.is_xbmc():
        import xbmc
        FAVOURITES_PATH = xbmc.translatePath("special://profile/favourites.xml")
    else:
        FAVOURITES_PATH = os.path.join(config.get_data_path(), "favourites.xml")
except:
    import traceback
    logger.error(traceback.format_exc())
```

It seems do not consider path substitution defined in advancedsettings.xml.
As workaround I changed to 

```
try:
    # Fijamos la ruta a favourites.xml
    if config.is_xbmc():
        import xbmc
        FAVOURITES_PATH = xbmc.translatePath("smb://192.168.1.103/kodi/userdata/favourites.xml")
    else:
        FAVOURITES_PATH = xbmc.translatePath("smb://192.168.1.103/kodi/userdata/favourites.xml")
except:
    import traceback
    logger.error(traceback.format_exc())
```

and now it seems to work. Probably I should not modify else statement, but for now it works :) I think there is a better way to fix this issue. 

My question is: at next update I'll lose these settings right? There a way to fix the issue on master code?

BR
Claudio

**Comment by Marplex** [comment]
Hi Claudio, you could fork this project, apply your fix and then open a "Pull Request" with your working code.

Your code can be applied in the master repository only if the admin accepts your request

**Comment by dentaku65** [comment]
smb://192.168.1.103 cannot be implemented for all
