### ISSUE TITLE
openload not working 

### ISSUE THREAD

**Issue by clamel77** [streamondemand/plugin.video.streamondemand#338]
Hello from yesterday 07 sept 2017 openload in not working anymore.. is it only my issue?

BR
Claudio

**Comment by As3ro** [comment]
Successo anche a me, ieri dopo un po' di utilizzo ha smesso improvvisamente di funzionare, oggi stessa cosa.

**Comment by costaplus** [comment]
Come sempre openload cambia qualcosa ... a breve verrà pubblicato un'aggiornamento
