### ISSUE TITLE
problema riproduzione

### ISSUE THREAD

**Issue by phede86** [streamondemand/plugin.video.streamondemand#339]
Nella sezione serie TV di Cineblog01 non ci sono elementi da visualizzare.

**Comment by costaplus** [comment]
Ciao,
prima cosa ti consiglio di resettare SoD per poi reinstallarlo, ma è anche conosciuto il problema su vecchie versioni di kodi.

**Comment by pfornaro** [comment]
Grazie mille per tenere vivo questo progetto, onestamente questo plugin è veramente indispensabile. Comunque confermo: anch'io aggiornando SoD non riesco a far partire openload. Proverò a resettare e reinstallare come hai suggerito.

**Comment by costaplus** [comment]
certo .. non è stato ancora ggiornarto!

**Comment by DjDiabolik** [comment]
a bene... come ho già fatto nella board aggiungo che insieme ai vai link openload nemmeno quelli di "streamango" vanno.
Cioè mi sembra strano che danno tutti un'errore nel player embeded quando invece da pc gli stessi mirror vanno tranquillamente :)

Spero di segnalare la cosa correttamente e che tale segnalazione sia cmq gradita........

**Comment by phede86** [comment]
Non funziona nemmeno speedvideo, wstream e streamin.

**Comment by DjDiabolik** [comment]
come no @phede86 ? Ieri sera i wstream funzionavano......... ci ho visto un filmetto io e i wstream andavano. 

Pure io cmq pensavo fossero streamin ma invece poi cineblog usa streamango non streamin...... mmmmmm...

**Comment by phede86** [comment]
Adesso mi dice sempre non c'è nessun elemento da visualizzare, prima succedeva per pochi canali invece adesso sono la maggior parte, anche installando da zero.

**Comment by DjDiabolik** [comment]
Strano perchè da me funzionano i mirror wstream.......

**Comment by errmax** [comment]
In Cineblog01 su alcune Serie TV (dipende dalle serie) non campaiono elementi da visalizzare in quanto hanno cambiato la dicitura da STAGIONE X a SEIRIE X
Ho postato un aggiornamento che risolve il problema ma non e' stato ancora accettato dal maintainer

**Comment by phede86** [comment]
Ok adesso vedo di nuovo la lista dei film e delle serie TV, rimane il problema di openload che non si apre e di alcune serie TV che non si aprono più.

**Comment by DjDiabolik** [comment]
mmmmmmmmmm.. per openload credo sia da fixare il server........ se non sbaglio c'è un issue dove c'è una soluzione perchè se ho capito da qualche tempo a questa parte ogni mirror di openload ha bisogno del pairing mentre prima non per tutto serviva e appunto i mirror del SOD non li richiedeva.
Magari il server va proprio fixato su questo aspetto... sparo a casaccio :)

**Comment by MrTruth0** [comment]
Il server di Openload funziona, e non necessita del pairing in SOD, se SOD da troppi problemi provate a cancellare la cache con qualche addon o reinstallatelo direttamente.

**Comment by DjDiabolik** [comment]
mmmmmm.... @phede86 aveva fatto l'installazione pulita io no........ io cmq riesco ad arrivare al punto dove dice "Guarda con [openload]" dove in quel caso dovrebbe comparire l'estensione.
Poi appunto dal momento che do Guarda carica un pò e non succede niente.........

Aspetta però....... io devo aggiornare alla 5.5.9......... poi aggiorno e ti so dire meglio :)

**Comment by errmax** [comment]
Non penso AKVideo sia uno dei server supportati (se mai esiste). Se invece intenti AKstream ... allora trovi la mia proposta di fix del file XML nel pull che  non e' stato ancora accettato ...
Aggingi:

                <patterns>
                        <pattern>[^:]+/akstream.(?:net|video)/(?:videos|v)([a-z0-9]+)</pattern>
                        <url>http://akstream.video/stream/\1</url>
                </patterns>

**Comment by DjDiabolik** [comment]
Azz.... sai c'è il 99% della possibilità che abbia sbagliato a leggere :)

Cmq interessante ma ho appena controllato e da me in effetti è cosi:
		<patterns>
			<pattern>http://akstream.(?:net|video)/(?:v|videos)/([a-z0-9]+)</pattern>
			<url>http://akstream.video/stream/\1</url>
		</patterns>

Non ho capito se devo aggiungere questo "patterns" da te suggerito oppure modificare quello che c'è già in pratica togliendo l'http e mettendo quel [^:].....

**Comment by errmax** [comment]
Entrambi gli approcci (aggiunta o sostituzione) dovrebbero funzionare ... forse sostituzione e' meglio ... in quanto e' sostanzialmente lo stesso ma piu generico

**Comment by DjDiabolik** [comment]
Ok poi provo ed eventualmente in caso di problemi posto qualche feedback.......

**Comment by DjDiabolik** [comment]
mmmmmmmmm..... allora non so perchè ma va in errore ora quando faccio l'edit.
Solo per dire che ho messo il nuovo "Patterns" ma Cineblog01 non mi sbagliavo.... dice proprio AKVideo e non AkStream e non penso sia la stessa cosa perchè ho appena provato con un film e continua a dire "Niente da riprodurre".
Inoltre ora come ora......... se apro cb01.eu anche da pc esce fuori una pagina bianca.......... boh.

**Comment by errmax** [comment]
In realta' se aggungi un XML e PY file nella directory /servers con le info corrette SoD dinamicamente le usera'.
Nota che nel caso di Akvideo vs AKstream ... non si tratta solo di un re-hosting di dominio ... ma le pagine akvideo sono completamente diverse da akstream .. cosi come la procedura per la generazione dei link video.
Pertanto anche se il nuovo XML e' facile da creare ... copia akstream e cambia

            <patterns>
                    <pattern>[^:]+/akvideo.stream/([A-Za-z0-9]+)</pattern>
                    <url>https://akvideo.stream/\1</url>
            </patterns>	

piu' ogni altro riferimento to akstream in akvideo ... per poter carpire i link video dovrai scrivere la pagina PY da solo ... quella di akstream non funziona.

Buona fortuna!!

**Comment by DjDiabolik** [comment]
Ah ecco.. quindi per l'xml basta cambiare mentre il file .py c'è appunto da capire come funziona il tutto.
Il fatto che dica "Niente da riprodurre" appunto vuol dire che magari l'xml è corretto però il .py appunto non risale al file che avvia lo streaming ?
Mmmmmm.... vediamo un'altra domanda:
Ma se io faccio modifiche al file .py come faccio poi a farlo ricaricaricare dal SOD ? Devo riavviare kodi o l'addons oppure basta che rilancio uno streaming e i file vengono ricaricati ?
Cmq credo che sia + "facile" fare il tutto reinstallando il kodi da pc invece che agire da OSMC almeno su pc posso di fatto modificare i file direttamente al volo senza usare ftp e simili..........

**Comment by DjDiabolik** [comment]
poi domani provo... probabile venga già fixato...

**Comment by pfornaro** [comment]
Scusate se mi intrometto, io non mi son mai cimentato in programmazione e robe simili ma se qulcuno mi spiegasse come effettuare il fix ad openload mi prenderei la briga di mantenerlo sempre aggiornato. Anche perchè ormai sono più le volte che è off rispetto le on

**Comment by costaplus** [comment]
Per quanto riguarda openload è uno dei server tra i più complicati, ma se vuoi provarci e pxcupartene ben venga, basta semplicemente aprire un link verso openload e visualizzando il sorgente/html trovare dove si trova il link diretto al video nomefile.mp4... quando sarai riuscito a trovarlo posso anche aiutarti con le regex python.
Prova a cercarlo e poi mi saprai dire, dopodichè ti do tuttw le informazioni utili...

**Comment by phede86** [comment]
Volevo informarla, che ora openload funziona su sod pure ita.Il 30/set/2017 18:58, costaplus <notifications@github.com> ha scritto:Per quanto riguarda openload è uno dei server tra i più complicati, ma se vuoi provarci e pxcupartene ben venga, basta semplicemente aprire un link verso openload e visualizzando il sorgente/html trovare dove si trova il link diretto al video nomefile.mp4... quando sarai riuscito a trovarlo posso anche aiutarti con le regex python.
Prova a cercarlo e poi mi saprai dire, dopodichè ti do tuttw le informazioni utili...

**Comment by costaplus** [comment]
Ciao Phede86, 
non avevo dubbi che la pureita fosse così veloce, un semplice copia e incolla da alfa-addon, puoi farlo anche tu!

Buon divertimento

**Comment by phede86** [comment]
non voglio denigrare il vostro lavoro, ho solo fatto un'osservazione, sono solo un utente non uno sviluppatore come lei.Il 03/ott/2017 11:23, phede92@yahoo.it ha scritto:Volevo informarla, che ora openload funziona su sod pure ita.Il 30/set/2017 18:58, costaplus <notifications@github.com> ha scritto:Per quanto riguarda openload è uno dei server tra i più complicati, ma se vuoi provarci e pxcupartene ben venga, basta semplicemente aprire un link verso openload e visualizzando il sorgente/html trovare dove si trova il link diretto al video nomefile.mp4... quando sarai riuscito a trovarlo posso anche aiutarti con le regex python.
Prova a cercarlo e poi mi saprai dire, dopodichè ti do tuttw le informazioni utili...

**Comment by dentaku65** [comment]
V5.6.4
openload funziona
cineblog01 fixed by ermax
