### ISSUE TITLE
[Domanda] SoD MediaServer

### ISSUE THREAD

**Issue by gerrydoro** [streamondemand/plugin.video.streamondemand#340]
Salve e scusate subito se ho aperto una issue per questa semplice domanda: dove trovo SoD MediaServer (o SoD PureITA MediaServer)? Grazie mille! :)

**Comment by costaplus** [comment]
da qualche parte sul forum mimediacenter qualcosa trovi, ma non penso che siano stati portati avanti e che qualcuno li abbia aggiornati!!
