### ISSUE TITLE
Più nessun supporto?

### ISSUE THREAD

**Issue by As3ro** [streamondemand/plugin.video.streamondemand#342]
Il progetto è stato abbandonato completamente? In tal caso un fork di covenant per l'ita non guasterebbe

**Comment by luX0r-reload** [comment]
Vai in releases e controlla...

**Comment by As3ro** [comment]
Questo è il progetto su github: https://github.com/Colossal1/plugin.video.covenant , vedremo

**Comment by errmax** [comment]
Quindi fine dei giochi? e' confermato?  ...  o e' solo un periodo di assestamento e riorg ?

**Comment by DjDiabolik** [comment]
E' il Pelis la carta che è stato abbandonato.............

**Comment by As3ro** [comment]
Vorrei dire comunque che come progetto era abbastanza complicato anche da mantenere, i server non erano gestiti nel migliore dei modi e forse ora Kodi potrebbe anche sorpassare questo problema come fa Covenant che è nato sulla base di krypton

**Comment by DjDiabolik** [comment]
mmmmmmmmmmm.... ne ho sentito parlare di Covenant perchè ho la repo di Colossus da mesi (ahahah.. porcellone :)) per altro e avendolo visto mi ero un pò informato su cosa fosse ma appunto ci sarebbe da ricavarne un fork italiano. 
In un recente passato personalmente ho provato a capire un pò come funzionasse il SOD e ho provato ad implementare diversi siti come channel oppure ieri sera ho provato a capire un pò come funzionasse l'implementazione di un nuovo server (AKStream che ora è diventato akvideo) ma non è che c'abbia capito abbastanza. So che ci vuole una buona conoscenza del phyton prima di tutto ed è quella che a mio avviso mi frega e non poco.............

**Comment by As3ro** [comment]
Ho visto che la versione PureITA sta continuando il suo lavoro...ma questa scelta forzata della skin non riesco a farmela andare giù.

**Comment by costaplus** [comment]
Ciao per quanto riguarda implementare SoD vi ricordo di aver creato una guida iniziale se la cosa interessa vi daremo delucidazioni in merito, cerchiamo sempre volontari e abbiamo anche creato un gruppo per chi ha voglia di iniziare a capire.
Per la pureITA tecnicamente è al pari di SoD tra canali e server(mero copia e incolla) per la forzatura della skin dovrebbe sistemare l'unico sviluppatore che c'è, purtroppo è da solo, potreste dare una mano a lui.
A voi la scelta!

**Comment by errmax** [comment]
"cerchiamo sempre volontari e abbiamo anche creato un gruppo per chi ha voglia di iniziare a capire."

Si puo' avere un po' piu di notizie? Che gruppo/dove?
Vorresti dire che ci potrebbe essere un futuro per un plugin che supporti i siti italiani?
Potrei suggerire due rige di "chiarimento" nel readme.txt ... giusto per settare le aspettative

Grazie

**Comment by DjDiabolik** [comment]
Riguardo al SOD ha un suo forum tutto suo la sezione italiana ragazzi....... è sul forum di MiMediaCenter. 
Li appunto trovate proprio diversi thread riguardo ad implementare canali e server sul SOD.... io come dico sopra c'ho provato un pò perdendoci un paio di serate tempo fà per cercare di implementare un sito ma come dissi all'epoca la cosa è + semplice da dirsi che da farsi. Poi magari è un limite mio e qualcun'altro apprende + facilmente non vi resta che provare.....
