### ISSUE TITLE
Problema Libreria

### ISSUE THREAD

**Issue by pfornaro** [streamondemand/plugin.video.streamondemand#346]
Ciao ragazzi, innanzitutto grazie per l'ultimo aggiornamento e per tenere vivo questo meraviglioso add-on.
Oggi volevo chiedere una piccola assistenza a chi ne sa più di me su questo argomento.
Praticamente ricordo che non molto tempo fa, quando aggiungevo una Serie TV alla libreria di SoD, riuscivo a ritrovarla direttamente nella sezione "Serie TV" del menù principale di Kodi. Ultimamente invece, ho perso completamente questa funzione e per ritrovare le mie serie devo per forza accedere a SoD e successivamente Libreria e Serie TV. Insomma, non un problemone però la cosa era utilissima. Non riesco a capire se è un problema mio o se è un problema comune e, soprattutto, se qualcuno è riuscito a trovare un fix. Ringrazio in anticipo chiunque riesca a darmi una mano.

**Comment by BlackSamba** [comment]
Da Kodi, imposta come sorgente file, la cartella della libreria di SOD.
Video - File - Aggiungi Video - Esplora -  e da li vai a ricercare la cartella della libreria.
Facendo così sincronizzi le due cose e quando aggiungi una serie su sod, la trovi anche su kodi

**Comment by pfornaro** [comment]
Non potrò mai ringraziarti abbastanza. Eppure era una cosa talmente logica e semplice... Grazie mille davvero!!
