### ISSUE TITLE
Openload non funziona

### ISSUE THREAD

**Issue by As3ro** [streamondemand/plugin.video.streamondemand#348]
È da un bel po' che non riesco più a vedere i film hostati su openload, praticamente è andato in cielo dopo l'ultimo update, provato a resettare tutto e urlresolver installato

**Comment by Kondor72** [comment]
Ho lo stesso identico problema dall'ultimo aggiornamento ma non credo dipenda dall'aggiornamento. Ho reinstallato una vecchia versione di SOD e non funziona lo stesso. Credo cmq che SOD non usi Urlresolver per Openload ma abbia uno script embedded. In pratica quando eseguo una ricerca, SoD mi da i risultati ma quando vado a cliccare su una fonte hostata su Openload non mi appare l'estensione del file sorgente (prima appariva .mp4) e quando clicco per avviare il file non accade nulla. Credo sia cambiato qualcosa nel modo in cui i server Openload gestiscono il link di apertura file video, strano che non ho visto molte segnalazioni a riguardo, tu sei il primo.

**Comment by luX0r-reload** [comment]
Openload va e viene. Di solito funziona la mattina ma il pomeriggio no.
Non so a cosa sia dovuto questo comportamento ma era già successo qualche volta con le versioni precedenti di SOD.
http://www.mimediacenter.info/foro/viewtopic.php?f=36&t=6821&start=940#p51788

**Comment by luX0r-reload** [comment]
Confermo che openload funziona solo la mattina. Appena provato con gli stessi contenuti che ieri e due giorni fa nel pomeriggio non andavano :)

**Comment by braguzz** [comment]
Scusate, a me e' da giorni che la cosa abbia avuto un tracollo di  funzionamento con molti server. 

In realta il 'sistema' mi ha dato sempre problemi e tempo fa davo la colpa al mio tvbox e dopo averlo cambiato mi sembrava di aver risolto.
Pero avevo ancora problemi dunque ho dato la colpa al router, ma dovo averne provati un paio i problemi si ripropongono.
Siccome siti tipo youtube funzionano bene, non so piu a chi dare la 'colpa', e prima di cambiare provider vorrei un consiglio da voi. Fatto sta che nel bel mezzo di una riproduzione, si va in buffering e da li cominciano gli smanettamenti infiniti. La cosa piu grave e' che sembra farlo maggiormente quando e' presente mia moglie...;)

Quindi o cambio moglie, o cambio provider, o... bo?

**Comment by costaplus** [comment]
Ciao braguzz, i tuoi porobleik possono essere tanti e uno dei tanti è se il tuo tvbox quando lo spegni si spegne o va solo in standby, questo fa siuramente la differenza, prova a seguire questa guida per resettare, ricorda di riavviare il tvbox di tanto in tanto importantissimo.
http://costaplus.altervista.org/guide/6-installare-sod-da-zero.html

Fammi sapere se poi hai risolto.

**Comment by luX0r-reload** [comment]
I problemi di buffering potrebbero dipendere da un jitter molto elevato relativo alla tua connessione.
Fai questo test nelle ore in cui di solito utilizzi SOD.

http://speedtest.mclink.it/

Naturalmente durante il test deve essere connesso al router soltanto il tvbox... niente altro.

**Comment by braguzz** [comment]
il tvbox lo spengo ogni tanto ma la cosa avveniva anche in passato con un altro tvbox che si spengeva e avviene tuttora con lo smartphone.. quindi escluderei una cattiva installazione o un allineamento mancato.
Non vorrei che il provider (infostrada) avesse dei filtri tipo traffic shaping , ma, ripeto, youtube funziona benissimo...

a volte ho problemi anche con contenuti non hd e in questi ultimi giorni non riesco praticamente a vedere quasi piu niente.. :(

**Comment by luX0r-reload** [comment]
Che youtube funzioni non c'entra niente. I filtri possono essere stati impostati solo per alcuni domini... e poi i server e l'infrastruttura di youtube non sono minimamente paragonabili a quelli, ad esempio, di openload. Una infrastruttura caxxuta può anche azzerare i problemi di jitter (e altri) che ti dicevo.
Fai il test che ti ho linkato. Io avevo gli stessi problemi. Ho risolto chiamando il provider e comunicandogli che avevo il parametro jitter altissimo, sopratutto in alcuni orari della giornata.

**Comment by braguzz** [comment]
ok grazie. Ho notato che il link che mi hai mandato necessita di flash, c'e' qualcosa di diverso magari una app?

**Comment by luX0r-reload** [comment]
Che io sappia no. Io di solito installo il plugin flash, faccio i test, e poi lo rimuovo ;)

**Comment by luX0r-reload** [comment]
Ricorda che i test li devi fare con il cavo, non con la wi-fi, altrimenti subentrano altri fattori...

**Comment by braguzz** [comment]
ok grazie

**Comment by Squalo08** [comment]
verissimo,openload non funziona...e molti canali non danno contenuti..è un peccato...

**Comment by Kondor72** [comment]
Se vi puó essere utile ho risolto cosí.
Effettuato download di SoD PureITA ultima versione da github e installata.
SoD PureITA mi apre i video Openload correttamente.
Ho copiato i file openload.py e openload.pyo (non openload.xml) dalla cartella servers di SoD PureITA alla cartella servers di SoD, e anche SoD or mi apre le sorgenti Openload correttamente. 
Per ora funziona

**Comment by As3ro** [comment]
Strano, ho provato anche con la PureITA e avevo lo stesso risultato, grazie lo stesso per l'informazione

**Comment by luX0r-reload** [comment]
Ma infatti non funziona neanche la pureita. Come ho già scritto dipende
all'orario. Openload di mattina funziona sia in sod che in pureita... Dopo
pranzo iniziano i dolori

Il 05 ott 2017 12:59 PM, "As3ro" <notifications@github.com> ha scritto:

**Comment by Kondor72** [comment]
Boh, a me funziona anche di notte, ho scaricato PureIta da qui:
https://github.com/orione7/plugin.video.streamondemand-pureita 
cliccando su Clone Files e Download Zip, c'é un fix di qualche giorno fa.

**Comment by luX0r-reload** [comment]
Di notte non ho mai provato... Prova dopo pranzo e alle 21 la sera... A me
fino a qualche giorno fa non andava neanche la pureita

Il 05 ott 2017 4:30 PM, "Kondor72" <notifications@github.com> ha scritto:

Boh, a me funziona anche di notte, ho scaricato PureIta da qui:
https://github.com/orione7/plugin.video.streamondemand-pureita
cliccando su Clone Files e Download Zip, c'é un fix di qualche giorno fa.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/streamondemand/plugin.video.streamondemand/issues/348#issuecomment-334482776>,
or mute the thread

**Comment by streamondemand** [comment]
@luX0r-reload questi aggiornamenti non sono della pureita, ma copiati da alfa-addon
https://github.com/alfa-addon/addon/tree/master/plugin.video.alfa/servers

**Comment by Squalo08** [comment]
Kondor72 la cartella dei server di pureita dove la trovo?perchè nella cartella userdata di pureita non è presente la cartella dei servers

**Comment by Kondor72** [comment]
@Squalo08 
cartella servers SoD su windows 7 = C:\Users\%tuonome%\AppData\Roaming\Kodi\Addons\Streamondemand\Servers
cartella servers SoDPureITa su windows 7 = 
C:\Users\%tuonome%\AppData\Roaming\Kodi\Addons\Streamondemand PureIta\Servers

Tieni presente che:
- AppData se non hai messo la spunta a 'Visualizza cartelle e file nascosti' nelle opzioni di Esplora Risorse, non lo vedi
- la directory che ti ho mandato é per Win7 ma credo per Win10 sia simile
- non sono certo di come si chiamino esattamente le cartelle di Sod e Sod pureita, non sono a casa in questo momento ma dovresti trovarle facilmente
- se il connettore openload.py di sod pureita é copiato da alfa-addon puoi anche tu fare copia incolla da alfa-addon

**Comment by luX0r-reload** [comment]
Mi state incasinando il cervello :)
Adesso da dove salta fuori questo alfa-addon? Cosa è? Un fork?

**Comment by dentaku65** [comment]
fixed with v5.6.1
