### ISSUE TITLE
Impossible to add TV series to library

### ISSUE THREAD

**Issue by r00zza** [streamondemand/plugin.video.streamondemand#350]
Whenever I look for a TV Series and try to add it to library it fails.

This was a very useful function because is very nice to have streamondemand series in the same folder of series downloaded on HD.

Do you have any hint to fix it?

Many thanks.

**Comment by FrankNa88** [comment]
I got the same error.
I'm tryng to fill up the Kodi Library with SoD Library... If I add some films everything goes fine, with TV series the process fails. Seems like it can't load it in the library.
Any help?

**Comment by dentaku65** [comment]
Log?

**Comment by FrankNa88** [comment]
Here they are... log and old

Il 30 Ott 2017 12:47 PM, "dentaku65" <notifications@github.com> ha scritto:

**Comment by dentaku65** [comment]
Il post è vuoto

**Comment by FrankNa88** [comment]
Ok. Ora provo con pastebin

**Comment by FrankNa88** [comment]
[kodi.log](https://github.com/streamondemand/plugin.video.streamondemand/files/1427202/kodi.log)
[kodi.old.log](https://github.com/streamondemand/plugin.video.streamondemand/files/1427203/kodi.old.log)

Eccoli....

**Comment by dentaku65** [comment]
Hai provato solo con seriehd?

Per piacere abilita i log nella configurazione di SOD e riprova a postare il log dopo che hai ricevuto l'errore

**Comment by FrankNa88** [comment]
Si ho provato solo con serie HD perchè uso quasi esclusivamente quello. Adesso provo con altri canali abilitando il log. Appena posso posto il log

**Comment by FrankNa88** [comment]
Ho abilitato il log nella configurazione di SoD. Ho provato ad aggiungere più di un canale, ma il risultato è sempre lo stesso. Ecco i log
[kodi log.log](https://github.com/streamondemand/plugin.video.streamondemand/files/1428139/kodi.log.log)
[kodi.old.log](https://github.com/streamondemand/plugin.video.streamondemand/files/1428140/kodi.old.log)

**Comment by FrankNa88** [comment]
News?

**Comment by MrTruth0** [comment]
Hai fatto un'installazione pulita di SOD ? non ho problemi del genere.

**Comment by MrTruth0** [comment]
Cancellare totalmente SOD dalla cartella addons e reinstallarlo

**Comment by FrankNa88** [comment]
Ok. Proverò. Tu hai popolato la libreria di Kodi collegandola a quella di SoD e ti funziona tutto?

**Comment by MrTruth0** [comment]
Si, provato su Android, Windows e linux, non mi da nessun tipo di problema.

**Comment by FrankNa88** [comment]
Ok. Adesso lo disinstallo pulisco un po' con Ares e riprovo. 
Grazie

**Comment by FrankNa88** [comment]
Niente da fare... ho provato con una installazione pulita (l'ultima versione), ma niente. 
Sempre lo stesso errore. Per i film tutto va a buon fine, con le serie no... si blocca al 50%.
Help please :(

**Comment by r00zza** [comment]
Io ho appena flashato Librelec 8.1.1 su Odroid C1+ e installato SoD quindi installazione pulitissima ma mi da lo stesso errore. Come a FrankNa88, i film vengono salvati nella libreria mentre le serie TV danno errore ancora prima di confermare il titolo della serie nel menù di selezione che solitamente si apriva quando aggiungevi una serie TV.

**Comment by FrankNa88** [comment]
Su Windows funziona tutto perfettamente. Non riesco a capire qual è il problema. 🤔😣

**Comment by FrankNa88** [comment]
Ragazzi ho risolto. Il problema sorge se la prima volta che si aggiunge un contenuto alla libreria al messaggio "Popolare la libreria di Kodi con SoD" si clicca "Si". Per chi come me ha fatto si è necessario disinstallare SoD poi, attivando la visualizzazione delle cartelle nascoste, si deve calcellare la cartella "plug.in.video.streamondemand... che si trova in Addon/File/Carlella Profilo/Addon_Data. Una volta eliminata reinstallare SoD e procedere con la popolazione della libreria cliccando "No" la prima volta che si aggiunge un contenuto.

**Comment by costaplus** [comment]
ciao FrankNa88 era quello che tentavamo di spiegarti, pulita vuol dire che oltre ad eliminare il plugin, eliminare anche i dati che permangono in userdata
Costaplus

**Comment by FrankNa88** [comment]
Graze. Non avevo capito ...

**Comment by r00zza** [comment]
ciao FrankNa88, facendo come dici tu si riesce ad aggiungere le serie alla libreria di SoD ma non vengono caricate nella libreria di Kodi quindi non vengono visualizzate nella cartella delle Serie TV.
Mi aiuti?

**Comment by FrankNa88** [comment]
Certo.
Devi dare il percorso alla libreria di kodi in modo tale che punti alle
cartelle della libreria di SoD.
Da video, procedi come per aggiungere una sorgente video qualunque... poi
esplora seguendo il percorso: Android/Data/org.
Xbmc.kodi/file/.kodi/userdata/addon_data/plugin.video.streamondemand/library/Series
(per i film la cartella CINE)
Poi assegna il contenuto, lo scraper e aggiorna la libreria di Kodi.

Il 03 Nov 2017 8:24 PM, "r00zza" <notifications@github.com> ha scritto:

ciao FrankNa88, facendo come dici tu si riesce ad aggiungere le serie alla
libreria di SoD ma non vengono caricate nella libreria di Kodi quindi non
vengono visualizzate nella cartella delle Serie TV.
Mi aiuti?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/streamondemand/plugin.video.streamondemand/issues/350#issuecomment-341802839>,
or mute the thread

**Comment by r00zza** [comment]
Grazie mille!
