### ISSUE TITLE
SOD non funziona da qualche mese

### ISSUE THREAD

**Issue by errelive** [streamondemand/plugin.video.streamondemand#352]
Buongiorno, ho sempre utilizzato all'addon streamondemand su due box android, (amiko a3 e amiko a4) ...
E' sempre funzionato, da circa un mese e mezzo non funziona più su entrambi i dispositivi, ho provato a disinstallarlo, reinstallarlo, cancellare cache, cancellare le cartelle nascoste, usare le opportune utility e **persino resettare l'intero box** ma nulla ... non funziona più
Quando parte e seleziono film/qualsiasi server/novità ... rimane con il cerchiolino del caricamento per poi uscire dopo alcuni minuti di attesa l'errore di connessione assente errore di struttura ...
Come posso risolvere il problema ?
Grazie !!!

**Comment by dentaku65** [comment]
SOD funziona correttamente, non conosco i box amiko; per piacere posta i log di kodi

**Comment by costaplus** [comment]
Ciao errelive, per i tvbox chiedi pure a me!
Domande:
Versione kodi usata ?
Se il box ha l'orario settato correttamente?
Quale fonte usi per avere lo script e quale versione?
Il box è collegato dierettamente alla lan o wifi ?

Se poi ci passi anche il log sarebbe molto utile per capire...

Costaplus

**Comment by errelive** [comment]
Ciao dentaku65 e costaplus, vi ringrazio delle risposte ricevute ... ieri sera ho effettuato ancora delle prove e alla domanda "il box è collegato direttamente alla lan o wifi" ho fatto ulteriori test ...
Non so per quale motivo **gli altri addon (tipo ip tv)** funzionavano in entrambe i box ma ... lo scenario era questo ...
Amiko a4 nel piano inferiore e Amiko a3 nel piano superiore ... il ripetitore wifi al piano superiore l'avevo configurato con lo stesso SSID del wifi di Fastweb del piano inferiore ... ho staccato il ripetitore wifi al piano superiore e **Kodi a funzionato alla grande come prima** ... ora non si spiega come mai il box del piano superiore perchè tentava di connettersi a quello inferiore e viceversa ... però ho risolto dandogli un altro nome SSID al ripetitore del piano superiore così da evitare che i box si connettano ad una rete wifi con minor potenza ...
Misteri dell'informatica e dei box tv :)
**Vi ringrazio tanto** perchè grazie a voi mi è venuta la "pulce nell'orecchio" per quanto riguarda la connessione ...
