### ISSUE TITLE
5.6.9 e.... i menù ora sono diventati in inglese ? Normale ?

### ISSUE THREAD

**Issue by DjDiabolik** [streamondemand/plugin.video.streamondemand#353]
Ragazzi.... sono andato a controllare nelle impostazioni e io che uso SOD su osmc è tutto settato in italiano però dopo l'aggiornamento (anche dopo un riavvio del mio Pi2 è rimasto cosi) ora mi ritrovo tutti i menù in inglese............ 

E' normale ?

**Comment by MrTruth0** [comment]
Fai un'installazione pulita di SOD dovrebbe risolvere ..

**Comment by DjDiabolik** [comment]
Mah...... è strana sta cosa. Avevo fatto un paio di riavvi e forse non bastava il solo riavvio.
Ieri sera sono andato a nanna........ oggi ho riacceso il Pi2 e il menù è tornato in italiano com'è sempre stato...... mistero risolto :)

**Comment by DjDiabolik** [comment]
mmmmmmmmm.... non dico che sia un problema grave perchè poi molto resta in italiano ma ho appena riacceso il Pi e i menù, apparentemente inspiegabilmente, mi sono ritornati in inglese dopo come detto erano tornati in italiano. Mah... in pratica ora non ho + il classico menù che dice "Categorie, Ricerca Globale ecc. ecc." ma bensi queste voci sono in inglese cosi anche come i vari menù anche nei canali.

Ho appena finito di fare addirittura la reinstallazione da zero...... ho riavviato osmc ma boh restano in inglese... Mistero della fede a questo punto :)

Come detto non è che sia un grosso problema ma mi chiedo perchè............... poi chiedo.... magari nelle configurazioni non è possibile aggiungere un'opzione per forzare il linguaggio ?

**Comment by MrTruth0** [comment]
Il sistema che usi é in italiano?

**Comment by DjDiabolik** [comment]
Si credo di si..... nel senso sul mio Pi2 ci gira OSMC ed è impostato in italiano ma non credo sia italiano.....

Cioè per fare un esempio... anche Windows su un pc non nasce in italiano ma forse nasce in inglese e poi c'è un Language Pack installato credo.

Cmq sia non è un problema grave perchè sono termini in inglese di uso comune..... però non mi spiego il perchè sto switch apparentemente insensato :)

**Comment by DjDiabolik** [comment]
Allora dopo diversi giorni e dopo diversi riavvi continuo ancora ad avere i menu principali e le voci principali in inglese veramente inspiegabile.
Ad esempio quando devo far partire la riproduzione non mi dice "Guarda" e l'estensione ma mi dice "Watch"... Lol.

Stavo addirittura pensando ad una soluzione drastica..... cioè se ho capito le traduzioni sono all'interno della cartella "Resource\Language" e stavo per prendere i file della cartella italian e piazzarli anche all'interno di quella inglese cosi male che vada in entrambi i casi i menu erano in italiano :)

Male che vada il ""problema"" (da notare le virgolette perchè in realta è una stupidaggine) si ripresenterà con il rilascio della 5.7.0 :)
