### ISSUE TITLE
Command line

### ISSUE THREAD

**Issue by doublex** [streamondemand/plugin.video.streamondemand#354]
Is it possible to resolve an URL from command line?
Best wishes!

**Comment by dentaku65** [comment]
In which fashion? What is the purpose?

**Comment by doublex** [comment]
Personal purpose.
It would be great to get the video-url from command-line, e.g. for
https://openload.co/f/miEoI5oT8JE/

Thanks a lot + best wishes!
Markus

**Comment by doublex** [comment]
I would donate $150 for a little hint...

**Comment by dentaku65** [comment]
you can check our code using python
