### ISSUE TITLE
Add IMDB Rating to media (film/series)

### ISSUE THREAD

**Issue by gabfus** [streamondemand/plugin.video.streamondemand#357]
Is possible to add rating of the media by using for example this python function?
https://github.com/jabbalaci/Movie-Ratings

If is possible you can active it with an option in your Stream On Demand.
The search are too slow but after you have the IMDB rating of the media to evaule the media to see.

Thanks

**Comment by dentaku65** [comment]
Hi, the search (Global Search) is not slow at all; on my RPI2 takes few seconds for a mainstream title (I mean a title present on almost all channels); the rating it is already present, when a title is displayed, calling/pushing the info button shows all data if matched from tmdb, with an high approximation between tittle and tmdb api in most cases.

**Comment by gabfus** [comment]
Hi, I have see that with info button the tmdb info is showed. 
Its possible to put this info after the main title? For example when I see the list of move in mode list or mode poster? 
Example list:
Star Wars: The Force Awakens (2015) 8.0/10 (715.735 users)
Star Wars - Gli ultimi Jedi (2017) 7,6/10 (246.162 users)
etc.

Thanks

**Comment by gabfus** [comment]
I have modify on my script platformtools.py for show the rating and votes after the title.

        # Formatear titulo
        if item.text_color:
            item.title = '[COLOR %s]%s[/COLOR]' % (item.text_color, item.title)
        if item.text_blod:
            item.title = '[B]%s[/B]' % item.title
        if item.text_italic:
            item.title = '[I]%s[/I]' % item.title

#TODO modify title, append rating
        rating = "n.d"
        if item.infoLabels:  
            if 'rating' in item.infoLabels:
                rating = str(item.infoLabels['rating']) 
        
        votes = "n.d"       
        if item.infoLabels:  
            if 'votes' in item.infoLabels:
                votes = str(item.infoLabels['votes'])

        item.title = '%s  [%s - %s]' % (item.title,rating,votes)
#TODO modify title + rating

If you would, you can add this on your release and also add an option check in configuration option for use or not this info in title.

Thanks for your work.
