### ISSUE TITLE
CB01 - AKVideo e Wstream mirror non vanno......

### ISSUE THREAD

**Issue by DjDiabolik** [streamondemand/plugin.video.streamondemand#359]
Il problema nel titolo......... per tutti i mirror in HD ci sono 2 source che vanno su pc mentre tutti i wstream e/o i mirror AKvideo non vanno sul SOD.
Per i Wstream dice... Attensa di connessione... poi dopo che dai OK sul guarda Mp4 non fa niente e torna alla lista dei mirror.
Per AKVideo invece va direttamente in errore............

**Comment by costaplus** [comment]
Mi spiace ma ....

SOD Farewell

SOD - Streamondemand chiuderà i battenti

Rimarrà un progetto privato solo per la Crew e i loro amici, non verranno rilasciate nuove release pubbliche e rimosse quelle attuali.

Le ragioni dietro questa decisione risiedono nella costante vampirizzazione del nostro lavoro da parte di soggetti che, per oscure ragioni o per gloria personale o altro, continuano a sfruttare il codice da noi scritto, senza:

- Riconoscere i credits nel codice o, peggio, sostituendoli
- Non cambiare nome all'addon (pureita, kltv), generando un'incomprensibile confusione e snaturando lo spirito del progetto
- Il persistere, con incuranza goffa, con le feature abilitate di torrent e download, nelle loro copie di SOD

Inutile dire che a nulla sono valse le richieste di modifica e di correttezza relativamente all'addon con tali soggetti. Questo atteggiamento parassitario, nonchè il dileggio ingaggiato in varie occasioni e sedi, ci ha portato a questa decisione e a farne le spese, purtroppo, saranno tutti gli utenti.

Per quanto riguarda il codice, SOD è sempre stato a disposizione di chiunque e, nell'ambito di una vera collaborazione, dell'indicazione dei credits e dello scambio delle soluzioni, mutuale (pelisalacarta, smytvshow, alfa, g2).

Gazie a tutti per averci seguito e sostenuto.

Good luck!

iSOD Crew

**Comment by DjDiabolik** [comment]
Peccato...... dal mio lato è stato bello finche è durato.
Poi anche io sarò costretto a passare ad altre versioni se verranno mantenute o meno........ altrimenti si ritorno al p2p com'è sempre stato.

Ciao e grazie ancora a tutti.........

**Comment by DjDiabolik** [comment]
Cmq sia sarà inevitabile la cosa.......... ma questa decisione, pur condivisibile, non causerà altro che un passaggio ad una delle tante versioni del SOD e molti blog che trattano argomentazioni kodi spingono già oggi all'utilizzo del pureITA se mai uno dovesse aver problemi col SOD stesso senza dare particolari spiegazioni un pò come succede anche con l'altro addons quale sportdevil.

Mantenere in vita il SOD richiederà pur tempo...... e se poi con scopiazzamenti vedi che altri se ne prendono i meriti può dar sicuramente fastidio ma questo potrebbe, a mio avviso, capitare con qualsisi app open source:
Negli ultimi tempi s'è messo il codice nascosto ma non è bastato ovviamente........... potreste provare ad appoggiare definitivamente il SOD fuori da GitHUB appoggiando l'aggiornamento dei server e dei canali su un servizio ftp....................
