### ISSUE TITLE
Nessun risultato ricerca

### ISSUE THREAD

**Issue by Testato** [streamondemand/plugin.video.streamondemand#360]
Da ieri cercando qualsiasi titolo non appare nessun risultato
Appaiono solo tre cartelle vuote.

Global Search - Search by Title -> esempio cerca Snowden

Testato su:
Linux - Android - Windows

**Comment by ad-git** [comment]
Confermo, anche da android box la ricerca non funziona più

**Comment by karkass11** [comment]
Stesso problema anche con osmc su raspberry PI

**Comment by Alexandersss** [comment]
Idem su tv box Android. Appaiono 3 cartelle senza nome, ovunque si tenti di accedere da ormai una settimana.

**Comment by ad-git** [comment]
Purtroppo Streamondemand ha chiuso i battenti. Non funzionerà più e non verranno rilasciate nuove release pubbliche.

**Comment by Alexandersss** [comment]
C'è per caso un comunicato di ciò che stai dicendo?

**Comment by Mello-Yello** [comment]
Mi ricordo che uno o due mesi fa avevano chiuso tutte le issue dicendo una roba simile

**Comment by Alexandersss** [comment]
Si, ho letto ora che hanno chiuso per via di tutti i vari fork, con cui speculavano sul sorgente, senza citarne la fonte. Nell'avviso di Telegram il team ha affermato che non avrebbero spento i server, ma solamente che non avrebbe più aggiornato il programma. Evidentemente ci hanno ripesanto. Comunque ci sono molte altre valide alternative, anche se questo era un'altro pianeta. Peccato.
