### ISSUE TITLE
Sod non visualizza risultati

### ISSUE THREAD

**Issue by spippete** [streamondemand/plugin.video.streamondemand#361]
Ciao!
Da una settimana sod 5.7.2 su kodi 17.6 non visualizza alcun risultato nè su ricerca libera, nè sulle liste preimpostate.
Ho provato a reinstallare anche cancellando la cartella impostazioni+riavvio+pulizia cache con ares e successiva reinstallazione sia della v5.7.0 che .2, ma nada...sempre lo stesso problema :.(...
Grazie per l’aiuto

**Comment by ad-git** [comment]
Purtroppo Streamondemand ha chiuso i battenti. Non funzionerà più e non verranno rilasciate nuove release pubbliche.
