### ISSUE TITLE
Non lo abbandonate

### ISSUE THREAD

**Issue by tmontanaro** [streamondemand/plugin.video.streamondemand#362]
Ragazzi, ma davvero volete abbandonare questo progetto?
Non c'è nessun plugin fatto bene come SOD ... se volete possiamo aiutarvi a continuare il lavoro!

**Comment by Mello-Yello** [comment]
Ma lo continuano, solo senza darti il codice

**Comment by tmontanaro** [comment]
Ah, allora bisogna correggere qualche bug perchè è da qualche settimana che non funziona più: quando si ricerca un film dà un elenco senza titoli!
