### ISSUE TITLE
Animeforce e animesenzalimiti non funzionano 

### ISSUE THREAD

**Issue by biru585** [streamondemand/plugin.video.streamondemand#366]
Potete controllare? Mi esce sempre "nessun elemento da visualizzare" quando entro in queste liste. 

Sod 5.7.4
Kodi krypton 
Win 8

**Comment by phede86** [comment]
Vero, li trova solo con la ricerca.

**Comment by MrTruth0** [comment]
Servono più dettagli, ho testato entrambi i canali e funzionano, solo il secondo sembra avere un problema con gli anime in corso.

**Comment by biru585** [comment]
in realtà il problema persiste, allego log`﻿17:13:43.088 T:547976429568  NOTICE: special://profile/ is mapped to: special://masterprofile/
17:13:43.088 T:547976429568  NOTICE: -----------------------------------------------------------------------
17:13:43.088 T:547976429568  NOTICE: Starting Kodi (17.6 Git:2017-11-20-163e112-dirty). Platform: Linux ARM 64-bit
17:13:43.088 T:547976429568  NOTICE: Using Release Kodi x64 build
17:13:43.088 T:547976429568  NOTICE: Kodi compiled Nov 20 2017 by GCC 5.4.0 for Linux ARM 64-bit version 4.4.13 (263181)
17:13:43.088 T:547976429568  NOTICE: Running on Ubuntu 16.04.3 LTS, kernel: Linux ARM 64-bit version 3.14.79-116
17:13:43.088 T:547976429568  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
17:13:43.088 T:547976429568  NOTICE: 4 CPU cores available
17:13:43.088 T:547976429568  NOTICE: ARM Features: Neon disabled
17:13:43.088 T:547976429568  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
17:13:43.088 T:547976429568  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/aarch64-linux-gnu/kodi
17:13:43.088 T:547976429568  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/aarch64-linux-gnu/kodi/addons
17:13:43.088 T:547976429568  NOTICE: special://masterprofile/ is mapped to: /home/odroid/.kodi/userdata
17:13:43.088 T:547976429568  NOTICE: special://envhome/ is mapped to: /home/odroid
17:13:43.088 T:547976429568  NOTICE: special://home/ is mapped to: /home/odroid/.kodi
17:13:43.088 T:547976429568  NOTICE: special://temp/ is mapped to: /home/odroid/.kodi/temp
17:13:43.089 T:547976429568  NOTICE: special://logpath/ is mapped to: /home/odroid/.kodi/temp
17:13:43.089 T:547976429568  NOTICE: The executable running is: /usr/lib/aarch64-linux-gnu/kodi/kodi.bin
17:13:43.089 T:547976429568  NOTICE: Local hostname: odroid64
17:13:43.089 T:547976429568  NOTICE: Log File is located: /home/odroid/.kodi/temp//kodi.log
17:13:43.089 T:547976429568  NOTICE: -----------------------------------------------------------------------
17:13:43.136 T:547976429568   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'OnLowBattery'
17:13:43.142 T:547976429568   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanSuspend'
17:13:43.143 T:547976429568   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanHibernate'
17:13:43.151 T:547976429568  NOTICE: load settings...
17:13:43.151 T:547976429568  NOTICE: AML device detected
17:13:43.190 T:547976429568  NOTICE: Found 1 Lists of Devices
17:13:43.190 T:547976429568  NOTICE: Enumerated PULSE devices:
17:13:43.190 T:547976429568  NOTICE:     Device 1
17:13:43.190 T:547976429568  NOTICE:         m_deviceName      : Default
17:13:43.190 T:547976429568  NOTICE:         m_displayName     : Default
17:13:43.190 T:547976429568  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
17:13:43.190 T:547976429568  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
17:13:43.190 T:547976429568  NOTICE:         m_channels        : FL,FR
17:13:43.190 T:547976429568  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
17:13:43.190 T:547976429568  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
17:13:43.190 T:547976429568  NOTICE:         m_streamTypes     : No passthrough capabilities
17:13:43.190 T:547976429568  NOTICE:     Device 2
17:13:43.190 T:547976429568  NOTICE:         m_deviceName      : alsa_output.platform-odroid_hdmi.analog-stereo
17:13:43.190 T:547976429568  NOTICE:         m_displayName     : ODROID-HDMI Analog Stereo
17:13:43.190 T:547976429568  NOTICE:         m_displayNameExtra: Analog Output (PULSEAUDIO)
17:13:43.190 T:547976429568  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
17:13:43.190 T:547976429568  NOTICE:         m_channels        : FL,FR
17:13:43.191 T:547976429568  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
17:13:43.191 T:547976429568  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
17:13:43.191 T:547976429568  NOTICE:         m_streamTypes     : No passthrough capabilities
17:13:43.197 T:547976429568  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
17:13:43.198 T:547976429568  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
17:13:43.198 T:547976429568  NOTICE: Default Video Player: VideoPlayer
17:13:43.198 T:547976429568  NOTICE: Default Audio Player: paplayer
17:13:43.198 T:547976429568  NOTICE: Disabled debug logging due to GUI setting. Level 0.
17:13:43.198 T:547976429568  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
17:13:43.198 T:547976429568  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
17:13:43.198 T:547976429568  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
17:13:43.199 T:547976429568  NOTICE: Loaded playercorefactory configuration
17:13:43.199 T:547976429568  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
17:13:43.199 T:547976429568  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
23:13:43.211 T:547976429568  NOTICE: Running database version Addons27
23:13:43.406 T:547976429568  NOTICE: ADDONS: Using repository repository.xbmc.org
23:13:43.406 T:547976429568  NOTICE: ADDONS: Using repository repository.colossus
23:13:43.406 T:547976429568  NOTICE: ADDONS: Using repository repository.xbmchub
23:13:43.439 T:547876761552  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 192 ms
23:13:43.487 T:547976429568  NOTICE: Checking resolution 16
23:13:43.487 T:547976429568  NOTICE: CWinSystemX11GLESContext::CreateNewWindow
23:13:43.494 T:547976429568  NOTICE: CWinSystemX11GLESContext::GetVisual() m_pGLContext:(nil) GetVisual
23:13:43.494 T:547976429568  NOTICE: Create new CGLContextEGL at CWinSystemX11GLESContext::CreateNewWindow, m_dpy=0x2eb3a80
23:13:43.540 T:547976429568  NOTICE: Using visual 0x41
23:13:43.979 T:547976429568  NOTICE: GL_VENDOR = ARM
23:13:43.979 T:547976429568  NOTICE: GL_RENDERER = Mali-450 MP
23:13:43.979 T:547976429568  NOTICE: GL_VERSION = OpenGL ES 2.0
23:13:43.979 T:547976429568  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
23:13:43.979 T:547976429568  NOTICE: GL_EXTENSIONS = GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer GL_KHR_no_error
23:13:44.310 T:547976429568   ERROR: GLES: Vertical Blank Syncing unsupported
23:13:44.564 T:547976429568   ERROR: Unable to load libcec.so.4, reason: libcec.so.4: cannot open shared object file: No such file or directory
23:13:44.588 T:547968024528  NOTICE: Running database version Addons27
23:13:44.590 T:547968024528  NOTICE: Running database version ViewModes6
23:13:44.592 T:547968024528  NOTICE: Running database version Textures13
23:13:44.597 T:547968024528  NOTICE: Running database version MyMusic60
23:13:44.604 T:547968024528  NOTICE: Running database version MyVideos107
23:13:44.606 T:547968024528  NOTICE: Running database version TV29
23:13:44.608 T:547968024528  NOTICE: Running database version Epg11
23:13:44.617 T:547976429568  NOTICE: start dvd mediatype detection
23:13:44.949 T:547976429568 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
23:13:45.188 T:547976429568  NOTICE: initialize done
23:13:45.188 T:547976429568  NOTICE: Running the application...
23:13:45.197 T:547976429568  NOTICE: starting zeroconf publishing
23:13:45.197 T:547976429568  NOTICE: starting upnp client
23:13:45.209 T:546517807056  NOTICE: ES: Starting UDP Event server on port 9777
23:13:45.211 T:546517807056  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
23:13:51.210 T:547339886544  NOTICE: [Covenant] ######################### COVENANT ############################
23:13:51.210 T:547339886544  NOTICE: [Covenant] ####### CURRENT COVENANT VERSIONS REPORT ######################
23:13:51.210 T:547339886544  NOTICE: [Covenant] ### COVENANT PLUGIN VERSION: 1.1.34 ###
23:13:51.210 T:547339886544  NOTICE: [Covenant] ### COVENANT SCRIPT VERSION: 1.00.030 ###
23:13:51.210 T:547339886544  NOTICE: [Covenant] ###############################################################
23:13:51.296 T:547331497936  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.6), DASH_SUPPORT_ADDON = True
23:13:51.740 T:547323109328  NOTICE: Indigo NOTICE: STARTING Indigo SERVICE
23:16:21.762 T:547876761552  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 192 ms
23:17:03.205 T:547491069904   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://www.animetubeita.com/wp-content/uploads/21407_anime_scenery.jpg
23:18:07.171 T:547976429568   ERROR: GetDirectory - Error getting plugin://plugin.video.streamondemand/?ewogICAgImFjdGlvbiI6ICJsaXN0YV9hbmltZSIsIAogICAgImNhdGVnb3J5IjogIkFuaW1ldHViZWl0YSIsIAogICAgImNoYW5uZWwiOiAiYW5pbWV0dWJlaXRhIiwgCiAgICAiZmFuYXJ0IjogImh0dHA6Ly93d3cuYW5pbWV0dWJlaXRhLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjE0MDdfYW5pbWVfc2NlbmVyeS5qcGciLCAKICAgICJpbmZvTGFiZWxzIjoge30sIAogICAgInRodW1ibmFpbCI6ICJodHRwOi8vaW1nMTUuZGV2aWFudGFydC5uZXQvZjgxYy9pLzIwMTEvMTczLzcvNi9jdXJzZWRfY2FuZGllc19hbmltZV9wb3N0ZXJfYnlfY2FyZWtvLWQzam56ZzkuanBnIiwgCiAgICAidGl0bGUiOiAiW0NPTE9SIGF6dXJlXUEtWlsvQ09MT1JdIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwOi8vd3d3LmFuaW1ldHViZWl0YS5jb20vbGlzdGEtYW5pbWUvIgp9
23:18:07.173 T:547976429568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.streamondemand/?ewogICAgImFjdGlvbiI6ICJsaXN0YV9hbmltZSIsIAogICAgImNhdGVnb3J5IjogIkFuaW1ldHViZWl0YSIsIAogICAgImNoYW5uZWwiOiAiYW5pbWV0dWJlaXRhIiwgCiAgICAiZmFuYXJ0IjogImh0dHA6Ly93d3cuYW5pbWV0dWJlaXRhLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjE0MDdfYW5pbWVfc2NlbmVyeS5qcGciLCAKICAgICJpbmZvTGFiZWxzIjoge30sIAogICAgInRodW1ibmFpbCI6ICJodHRwOi8vaW1nMTUuZGV2aWFudGFydC5uZXQvZjgxYy9pLzIwMTEvMTczLzcvNi9jdXJzZWRfY2FuZGllc19hbmltZV9wb3N0ZXJfYnlfY2FyZWtvLWQzam56ZzkuanBnIiwgCiAgICAidGl0bGUiOiAiW0NPTE9SIGF6dXJlXUEtWlsvQ09MT1JdIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwOi8vd3d3LmFuaW1ldHViZWl0YS5jb20vbGlzdGEtYW5pbWUvIgp9) failed
23:18:42.190 T:547491069904   ERROR: CPythonInvoker(15, /home/odroid/.kodi/addons/plugin.video.streamondemand/default.py): script didn't stop in 5 seconds - let's kill it
23:18:43.043 T:547516141520   ERROR: ######## ERROR #########
23:18:43.043 T:547516141520   ERROR:     [streamondemand.platformcode.launcher.run] Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 262, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/channels/animetubeita.py", line 112, in lista_anime
                                                for scrapedurl, scrapedtitle in scrapedAll(item.url, patron):
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/channels/animetubeita.py", line 345, in scrapedAll
                                                data = httptools.downloadpage(url).data
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 253, in downloadpage
                                                if downloadpage(auth_url, headers=request_headers, replace_headers=True).sucess:
                                              File "/home/odroid/.kodi/addons/plugin.video.streamondemand/core/httptools.py", line 150, in downloadpage
                                                logger.info("Dominio: " + urlparse.urlparse(url)[1])
                                              File "/usr/lib/python2.7/urlparse.py", line 137, in urlparse
                                                def urlparse(url, scheme='', allow_fragments=True):
                                            SystemExit
23:20:10.056 T:547976429568  NOTICE: Storing total System Uptime
23:20:10.057 T:547976429568  NOTICE: Saving settings
23:20:10.063 T:547976429568  NOTICE: Saving skin settings
23:20:10.065 T:547976429568  NOTICE: stop all
23:20:10.065 T:547976429568  NOTICE: stop player
23:20:10.065 T:547976429568  NOTICE: ES: Stopping event server
23:20:10.065 T:547976429568  NOTICE: stopping upnp
23:20:10.217 T:547976429568  NOTICE: stopping zeroconf publishing
23:20:10.595 T:546517807056  NOTICE: ES: UDP Event server stopped
23:20:10.597 T:547976429568  NOTICE: stop dvd detect media
23:20:10.655 T:547976429568  NOTICE: clean cached files!
23:20:10.814 T:547323109328  NOTICE: Indigo NOTICE: CLOSING INDIGO SERVICES
23:20:11.134 T:547976429568  NOTICE: closing down remote control service
23:20:11.136 T:547976429568  NOTICE: stopped
23:20:11.336 T:547976429568  NOTICE: destroy
23:20:11.336 T:547976429568  NOTICE: unload skin
23:20:11.350 T:547976429568 WARNING: Cleanup: Having to cleanup texture button-nofocus.png
23:20:11.350 T:547976429568 WARNING: Cleanup: Having to cleanup texture button-focus.png
23:20:11.485 T:547976429568  NOTICE: unload sections
23:20:11.494 T:547976429568  NOTICE: special://profile/ is mapped to: special://masterprofile/
23:20:11.507 T:547976429568  NOTICE: application stopped...`
