### ISSUE TITLE
Inserimento funzione backup in Stream On Demand

### ISSUE THREAD

**Issue by Dance68** [streamondemand/plugin.video.streamondemand#368]
E' possibile inserire nel menu' delle preferenze (e/o in qualche altra parte) una voce relativa al **backup** delle impostazioni ? (libreria, episodi/stagioni gia' visti/e, preferenze, dati ecc.. ), sarebbe molto utile in caso di reset e/o reinstallazione forzata o semplicemente di passaggio delle impostazioni tra un Kodi e l'altro (piu' postazioni con SOD installato, nel mio caso PC e TVBox).
Grazie

**Comment by MrTruth0** [comment]
Ci sono già vari tools per kodi https://kodi.wiki/view/add-on:backup

**Comment by Dance68** [comment]
Io intendevo un backup solo per SOD senza dover fare il backup di Kodi intero, altrimenti non avrei chiesto.

**Comment by dentaku65** [comment]
copi a mano la directory di sod in userdata con un cron job
