### ISSUE TITLE
Ilgeniodellostreaming non parte

### ISSUE THREAD

**Issue by jonreal64** [streamondemand/plugin.video.streamondemand#369]
Ilgeniodellostreaming non parte

**Comment by dentaku65** [comment]
Allega log

**Comment by jonreal64** [comment]
si vede il log?

**Comment by Dance68** [comment]
Se puo' essee d'aiuto agli sviluppatori riporto un mio test :
per quanto riguarda il canale "Il genio dello streaming", mi sono collegato al sito ed individuata la presenza di una serie a caso "1992", ho avviato lo streaming ed e' partito senza problemi. Ho ricercato quindi la stessa serie con SOD (sia nelle serie TV, sia nei film) e non mi ha rilevato nulla (nessun errore), quindi il canale praticamente viene bypassato. Dimenticavo, naturalmente mi sono accertato che nelle preferenze ci fosse la selezione sul canale.

**Comment by dentaku65** [comment]
fixed in 5.7.6

**Comment by geniostreaming** [comment]
http://ilgeniodellostreaming.ws
