### ISSUE TITLE
Openload su SERIEHD

### ISSUE THREAD

**Issue by lucabz** [streamondemand/plugin.video.streamondemand#370]
Non riesce a risolvere il link ed avviare lo streaming

**Comment by dentaku65** [comment]
fixed in 5.7.6

**Comment by lucabz** [comment]
Purtroppo anche con la 5.7.6 non si è risolto. Ora non viene nemmeno rilevato il link mentre prima lo rilevava ma non lo avviava.

**Comment by Dance68** [comment]
Quello che a Te succede con Openload, a me succede con SpeedVideo, ci sono i link, poi spariscono, poi magicamente riappaiono e a volte vanno.
