### ISSUE TITLE
problema speedvideo-MEGADRIVE

### ISSUE THREAD

**Issue by sarumans** [streamondemand/plugin.video.streamondemand#371]
Tutti i link megadrive non vanno
Con l'ultimo aggiornamento speedvideo non va più prima invece nessun problema.
Ho riscontrato il problema cercando la serie magicians nei seguenti canali:
- piratestreaming
- vediserie 
- serietvu
ed altri

invece su SOLOSTREAMING--> non apre proprio i link 
MEGADRIVE:
-guardarefilm;
- altadefinizioneZone

**Comment by dentaku65** [comment]
log, kink di esempio... hai controllato che su browser fuzionino?
