### ISSUE TITLE
Inserimento sito Alta definizione . bid

### ISSUE THREAD

**Issue by Dance68** [streamondemand/plugin.video.streamondemand#372]
Salve, uso da parecchio il sito riportato nel titolo https://altadefinizione.bid/ , e' molto completo e contiene sia Film, sia Serie TV, inoltre si possono scegliere vari player (Speedvideo–Wstream–Openload–Rockfile–Nitroflare), lo ritengo molto affidabile.

Se possibile, chiedo quindi che venga inserito tra i canali nella speranza che sia anche compatibile con l'aggiunta delle serie/episodi, nella libreria di SOD. 
Grazie

**Comment by MrTruth0** [comment]
Il sito c'è già, è chiamato "AltadefinizioneClub"

**Comment by Dance68** [comment]
Ok scusami, se sapevo che era lo stesso non l'avrei chiesto per non creare disguidi,  grazie per la pronta risposta !

**Comment by MrTruth0** [comment]
Nessun problema :)
