### ISSUE TITLE
Serie HD

### ISSUE THREAD

**Issue by mattitotti** [streamondemand/plugin.video.streamondemand#374]
Buonasera ragazzi,potete gentilmente sistemare il canale Serie HD, dentro ogni serie TV dice che non ci sono elementi da visualizzare.

**Comment by MrTruth0** [comment]
Info ? Log ?

**Comment by mattitotti** [comment]
Mi dispiace ma non ho il PC al momento...però posso assicurare che il bug c'è...su tutte le serie TV che stanno su Serie HD, c'è la numerazione Delle puntate ma non ci sono i link per vederle...

**Comment by mattitotti** [comment]
Mi dispiace ma non ho il PC al momento...però posso assicurare che il bug c'è...su tutte le serie TV che stanno su Serie HD, c'è la numerazione Delle puntate ma non ci sono i link per vederle...

**Comment by MrTruth0** [comment]
Tranquillo, è stato fixato

**Comment by mattitotti** [comment]
Dove devo scaricare il fix? Perché a me ancora non si sistema...o verrà fixato nella prossima release?

**Comment by MrTruth0** [comment]
Sarà disponibile dalla prossima Release

**Comment by dentaku65** [comment]
fixed with 5.7.7
