### ISSUE TITLE
Problema doppio aggiornamento

### ISSUE THREAD

**Issue by phede86** [streamondemand/plugin.video.streamondemand#375]
Salve, con la nuova repo di sod, l'addon viene aggiornato due volte, la prima voltaautomaticamente tramite addon e la seconda volta all'apertura dell'addon mi viene notificato un nuovo aggiornamento anche se in realtà io l'avevo già aggiornato in precedenza, é possibile rimuovere la funzione dell'aggiornamento all'interno dell'addon ?
Grazie.

**Comment by dentaku65** [comment]
Prova disabilitare gli aggiornamenti automatici all'interno del repository come descritto qui:
http://koditips.com/disable-automatic-updates-kodi-addons-repos/
Vedi il paragrafo "How to Disable Automatic Updates to Specific Kodi Addons & Repos".

Tieni conto che il repository è stato pensato per l'installazione da zero dell'addon; se hai già sod installato l'update automatico al suo interno è quello che conta; inoltre l'aggiornamento interno è immediato al rilascio della nuova release, mentre l'aggiornamento automatico tramite repository ha dei tempi più lunghi per via della sicronizzazione della nuova chiave md5 con github dove il repository risiede.
