### ISSUE TITLE
Ricerca vuota

### ISSUE THREAD

**Issue by ing76** [streamondemand/plugin.video.streamondemand#378]
cercando qualsiasi titolo (ricerca globale -> cerca titolo) non appare nessun risultato
Appaiono solo tre cartelle vuote.
Nessun problema con la ricerca nei canali

Sembra si sia interrotto il collegamento fra SOD e TheMovieDB
(Stesso problema con tutte le ricerche che richiedono metadati a TMDB o TVDB) 

Testato su:
Linux Debian - Android - Openelec RBPi3

**Comment by MrTruth0** [comment]
Fixato nella v5.7.9
