### ISSUE TITLE
Errore di connessione o canale web potrebbe aver cambiato la struttura

### ISSUE THREAD

**Issue by franci07** [streamondemand/plugin.video.streamondemand#382]
Ciao,

ho installato con successo SoD 5.8.0.
Riesco a navigare i menu in lungo ed in largo. L'unica cosa su cui ho un problema è all'avvio dei video.
Kodi tenta di caricarli, dopo pochi istanti riporta sempre lo stesso messaggio (vd. in oggetto). Il problema si ripete su qualsiasi fonte video che cerco di accedere, mentre SoD va che una bomba.

Riporto il link al log: https://paste.kodi.tv/obubuxuges

Vi ringrazio per il supporto.

**Comment by MrTruth0** [comment]
Non ho questo problema 🤔 Qual'è uno dei canali che ti da questo problema ? e con quale film ?

**Comment by franci07** [comment]
Buongiorno,

nel log ho provato ad entrare dal menù "più Popolari" e navigare tra "The Big Bang Theory", aver tentato di far andare la prima puntata con "Cineblog 01"  arrivando poi alla scelta del sito.
Per Eurostreaming ad esempio mi si ferma prima alla scelta dell'episodio.  
Poi ho provato The Walking Dead, sempre stessa musica.
Per quanto riguarda i film ho cercato (la ricerca funziona alla grande) Deadpool2 e cercato di vedere.
Purtroppo l'errore è pressochè simile in tutti i titoli/provider provati.
Ho provato anche a cambiare rete utilizzando il tethering per verificare che non sia un mio problema di rete. Il router ha i DNS di Google impostati.

Grazie mille

**Comment by MrTruth0** [comment]
Come diciamo già nel gruppo, non supportiamo Kodi 18 perchè in alpha.
