### ISSUE TITLE
possibilita di implementazione resolveurl

### ISSUE THREAD

**Issue by snikege** [streamondemand/plugin.video.streamondemand#384]
ciao ragazzi il plugin è perfetto ma essendo possessore di account real debrid dite che c'è la possibilita di iplmentare resolveurl (o Urlesolver) per evitare il fastidioso buffering di siti quali openload?grazie attendo riscontri.

qui c'è il sito che spiega come implementarlo
https://koditips.com/resolveurl-kodi-dependency-urlresolver-fork/

https://github.com/jsergio123/script.module.resolveurl e qui il github di Jsergio

**Comment by snikege** [comment]
https://github.com/jsergio123/script.module.resolveurl this is the source of the plugin

**Comment by dentaku65** [comment]
nessuno dei dev possiede account real debrid; se hai una soluzione prova ad implementarla autonomamente e proponi un commit
