### ISSUE TITLE
add  sezione anime tali URL per piacere 

### ISSUE THREAD

**Issue by Samuelebaroni1979** [streamondemand/plugin.video.streamondemand#385]
Buonasera spett Team Sod,
Chiedo cortesemente se nella sezione anime di Sod potreste aggiungere tali URL 
http://www.animesubita.org/
https://toonitalia.org/

Cordiali saluti 
Samuele

**Comment by MrTruth0** [comment]
Animesubita sarà nella prossima release

**Comment by Samuelebaroni1979** [comment]
Vi comunico che downloadme ha cambiato URL vi fornisco nuova URL
funzionante https://www.downloadme.gratis/

Se volesse aprisse un nuova segnalazione lo farò.

Buona continuazione di giornata
Samuele
