### ISSUE TITLE
La funzione "Novita'" in "Serie TV", restituisce risultati solo su alcuni canali

### ISSUE THREAD

**Issue by Dance68** [streamondemand/plugin.video.streamondemand#387]
Da alcuni giorni, in SOD - Novita' - Episodi Serie TV, ottengo solo risultati dai canali :
- Fastsubita
- GuardaSerie.click  
- Italia-film.co
- Italia Serie
- SerieTVU          
- Solo Streaming                                             
anche se in SOD - Configurazione - Impostazioni Novita' - Canali inclusi in Episodi Serie TV, sono inclusi tutti i canali. Quando SOD ricerca si vede che li prende in considerazione tutti ma, restituisce solo risultati per i suddetti.  Mi sono assicurato che, in alcuni canali (ad es. Film Per Tutti) senza alcun esito nella ricerca, in realta' le novita' ci fossero, guardando direttamente nei siti web. Mi sono limitato a testare solo le "Novita'" in "Episodi Serie TV" e non in "Film, Episodi Anime e Documentari" che probabilmente avranno lo stesso problema. Sara' cambiata la struttura di quelli che non vengono rilevati. Si puo' sistemare ? Grazie

**Comment by MrTruth0** [comment]
Chiarito su telegram.
