### ISSUE TITLE
Problema Solo-Streaming.com

### ISSUE THREAD

**Issue by alex1901997** [streamondemand/plugin.video.streamondemand#41]
Per piacere potete risolvere...ogni volta che vado su un episodio attendo il caricamento ma mi porta su un'altra pagina dove non risiede nessun link , ma sul web mi fa vedere il video della serie o episodi a parte. Grazie a tutti per il grande lavoro che fatte!!!!

**Comment by dentaku65** [comment]
Ma un esempio?

**Comment by alex1901997** [comment]
Per esempio nella Categoria Anime/Ultimi episodi aggiornati non funziona manco uno:/

**Comment by DjDiabolik** [comment]
So che il problema è un'altro ma segnalato che anche CasaCinema ha un problema dovuto al caricamento dei link.
In pratica quasi tutte le sezioni........... le liste dei titoli vengono caricate ma poi quando si da l'ok per ottenere le "fonti", nel mio caso OSMC, rimane con lo spin "Attendere Prego" all'infinito in basso a destra senza mai andare in timeout e se si ferma la ricerca OSMC va in stallo/crash tant'è che si deve riavviare il Pi2.........

**Comment by alex1901997** [comment]
Buona fortuna con casa cinema allora 💪 sperò che anche il mio di problema venga risolto

**Comment by dentaku65** [comment]
Anime non funzionano neanche sul sito di solo-streaming, quindi di consegenza anche su SOD puoi scrivere direttamente a loro (magari se controllavi prima era meglio); casacinema funziona correttamente; controlla la tua installazione http://www.mimediacenter.info/foro/viewtopic.php?f=36&t=7803

**Comment by DjDiabolik** [comment]
In quando a casacinema.............. io ho segnalato la cosa circa 8 giorni fà poi ovviamente ho evitato di usarlo.

Come ho detto la cosa non riguarda la ricerca vera e propria ma bensi la ricerca poi effettiva delle fonti per lo streaming stesso.
Cioè ad esempio........ vai nei titoli dei film....... ne selezioni uno e in teoria dopo x secondi dovresti ottenere le varie fonti quali openload nowvideo ecc. ecc. mentre invece io notavo che questa ricerca diventava infinita e ho lasciato li il tutto anche diversi minuti col risultato che alla fine OSMC va completamente in stallo tant'è che dovevo spegnere e riaccendere il Pi2.

In quando a controllare la mia installazione........ bè a dire il vero nel link è suggerito come fare un'installazione da zero.
Io posso anche provare...... non è un problema...... magari ci sta pure che installazioni su installazioni qualche file sia rimasto obsoleto o parzialmente corrotto in quando da creare problemi qua e la.

Ti/Vi posterò futuri feedback in futuro magari.................... cmq sia se canalecinema non va non è poi sto problema perchè poi alla fine non è l'unico canale :)
