### ISSUE TITLE
Nuovi canali💪😍

### ISSUE THREAD

**Issue by alex1901997** [streamondemand/plugin.video.streamondemand#42]
eanimelovers.blogfree.net  e animehdita.altervista.org potreste aggiungere nella nuova release questi fantastici canali grazie  :) se è possibile anche sistemare solo-streaming.com che non riconosce alcuni link per aprire i video come animehdita 👏👏👏

**Comment by dentaku65** [comment]
Difficile che ci si impegni su canali che sono ospitati da domini terzi; la crew non si attiva per quelli.... se qualche volontario lo crea e fà un pull si potrebbe considerare
