### ISSUE TITLE
5.3.8 - Ricerca Infinita..... 

### ISSUE THREAD

**Issue by DjDiabolik** [streamondemand/plugin.video.streamondemand#46]
Allora ragazzi... ieri sera ho provato a fare una ricerca Globale e alla fine sia che la fai usando la parte "Film" e sia la parte "Serie TV" (che poi quali sono le differenze ?? Alla fine se lo storico delle ricerche è condiviso tra le 2 differenti ricerche cosa cambia fare una o l'altra ??) la ricerca parte ma di fatto non finisce mai e si blocca a poco prima della fine con a schermo la dicitura "Attendere Prego" in basso a destra che gira all'infinito.

Unica soluzione è spegnere e riaccendere, nel mio caso, il Raspberry Pi2 con su l'ultima release del OSMC (basato sul kodi 16.1).

La chiave di ricerca che ho provato è "Sanford" (cercavo, anche se so non si trova niente credo) ma ho provato poi con altre chiavi e il risultato non cambia........ cambia solo la barra di progresso che a volte sembra bloccarsi poco prima della fine altre a + o - il 50% e altre a differenti %. E' come se la ricerca per qualche sito non andasse in timeout o qualcosa del genere.......................

Vi risulta ?

**Comment by dentaku65** [comment]
Fixed in 5.3.9
