### ISSUE TITLE
Ricerca globale - Ricerca sul server

### ISSUE THREAD

**Issue by spritekiller** [streamondemand/plugin.video.streamondemand#50]
Cercando una serie tv sul server
Tutti i canali > Serie HD > Cerca > "il trono"
appare la voce cercata con tutte le puntate
Se la ricerca viene fatta 
Ricerca globalre > cerca serie tv > "il trono"
appare solo la voce che si riferisce al server Guardarefilm con solo l'ultima stagione

Precedentemente a tutto ho controllato 
Configurazione > Impostazione della ricerca globale > scegli canali da includere nella ricerca > Serie HD
e risulta spuntato

Grazie

**Comment by dentaku65** [comment]
La ricerca globale ha un timeout di 75 secondi, probabilmente in questo tempo non riesce a scandagliare tutti i canali per enne ragioni: sistema lento, banda, siti irraggiungibili; calcola che la ricerca viene fatta su una 20ina di canali; prova a disabilitare qualche canale o fare la ricerca con multithread abilitato/disabilitato... in un futuro potremmo considerare l'impostazione del timeout dai settings... la ricerca globale è troppo variabile con tanti canali insomma.
