### ISSUE TITLE
CinemaLibero

### ISSUE THREAD

**Issue by Kolifanes** [streamondemand/plugin.video.streamondemand#52]
Non restituisce i nomi degli episodi e non funziona il cerca. E' uno dei canali migliori. Grazie

**Comment by dentaku65** [comment]
Il canale è stato sistemato ieri; riavvia kodi per aggiornarlo

**Comment by Kolifanes** [comment]
Guarda che l'ultimo aggiornato è di 11 giorni fa https://github.com/streamondemand/plugin.video.streamondemand/blob/master/channels/cinemalibero.py
