### ISSUE TITLE
CinemaLibero 2

### ISSUE THREAD

**Issue by Kolifanes** [streamondemand/plugin.video.streamondemand#53]
Riapro. L'aggiornamento non risulta https://github.com/streamondemand/plugin.video.streamondemand/blob/master/channels/cinemalibero.py

**Comment by dentaku65** [comment]
ops avevo inteso casa-cinema... cmq sul forum http://www.mimediacenter.info/foro/viewtopic.php?f=37&t=8000#p35613

**Comment by dentaku65** [comment]
sistemati gli episodi

**Comment by dentaku65** [comment]
:+1:
