### ISSUE TITLE
Canali Non Funzionanti

### ISSUE THREAD

**Issue by JLDon** [streamondemand/plugin.video.streamondemand#55]
Aiuto, da 12 ore non é piú possibile collegarsi a gli archivi di "GuardareSerie", che risulta vuoto e di "Altadefinizione.01", di conseguenza i propri contenuti salvati in libreria o in superfavourites, risultano non raggiungibili e inutilizzabili,risolvete grazie,cosí posso guardare qualcosa.

**Comment by mrhook11** [comment]
ciao a tutto io anche ho lo stesso problema.. spero risolvete al piu presto possibile.. grazie a tutti

**Comment by kubetts** [comment]
Stesso problema su cb01,  piratestreaming, filmpertutti, e altri. Vers 5.4.1

**Comment by mrhook11** [comment]
se installo un altra versione pensi che io possa risolvere qualcosa? grazie ancora

**Comment by Dr-Zer0** [comment]
Aggiornati i domini dei canali

**Comment by JLDon** [comment]
Ancora per altadefinizione01 ci sono dei problemi,salvati dei contenuti non si dovrebbe in teoria aggiornarli, cercandoli e aggiungendoli nuovamente,spero.
