### ISSUE TITLE
Connettori  e altre cose che non vanno

### ISSUE THREAD

**Issue by JLDon** [streamondemand/plugin.video.streamondemand#57]
###  Connettori https://gyazo.com/a6c05e796f85ff336f2d2402aeddef4c

> Contenuti salvati che non si aprono eccetto se si preme back (SOLO SE VIENE UTILIZZATO KODI SU PC) 
## https://gyazo.com/d27994803495c67df4bda472da0269d2
Ed e cosí con tutti i film di altadefinizione.01
Grazie.

**Comment by dentaku65** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=36&t=7803
