### ISSUE TITLE
Aggiornamenti SOD su OSMC

### ISSUE THREAD

**Issue by RaspberryPiZero** [streamondemand/plugin.video.streamondemand#60]
Salve, 
Premetto che utilizzo **SOD** sia su Raspberry che su Vero 2 con _OSMC_ (e funziona benissimo) con la sola eccezione che **non mi compaiono gli aggiornamenti automatici nel menu principale**. Ho già provato con varie formattazioni, wipe addon_data etc, ma niente. Ogni volta devo andare su Preferenze > Controlla Aggiornamenti per far apparire la finestra di aggiornamento. Il problema si risolve se cancello la cartella "Temp" di Kodi. Il problema non capita per Kodi Mac e Librelec. Ho già chiesto agli sviluppatori di OSMC e mi hanno avvertito che non è consigliabile cancellare la cartella "Temp" e che non possono aiutarmi visto che SOD non è un Add-On ufficiale.

Immagino a questo punto, andando ad esclusione, che il problema sia proprio di OSMC, che a quanto pare ha qualche problema con la cache dei menu. Vorrei chiedere se è possibile da parte vostra trovare un modo per schedulare questo controllo aggiornamenti da preferenze, oppure se è possibile avere una repository dove l'addon si aggiorna in automatico con Kodi, bypassando quindi questo problema di cache dei menu. È possibile?

Grazie

**Comment by dentaku65** [comment]
PiZero grazie!
Utilizzo anche io OSMC e ho lo stesso problema con gli aggiornamenti 
http://www.mimediacenter.info/foro/viewtopic.php?f=37&t=8060
pensavo fosse un problema dell'addon e invece riporti questa notizia... puoi indicarmi il tread su OSMC che hai aperto?

**Comment by RaspberryPiZero** [comment]
Ciao Dentaku65 e grazie mille per la risposta. Sono un vostro grande fan e il fatto che forniate anche supporto è un bella cosa. Per adesso non ho problemi con gli aggiornamenti dei canali (mi basta riavviare e vedo la rotellina in basso a sinistra girare con i vari nomi dei canali che si stanno aggiornando). Il mio problema in particolare è proprio con l'aggiornamento dell'Add-on. In pratica nel menu principale dell'add-on non mi compare la finestra e la voce "Aggiorna alla versione X.X.X". Devo cliccare su aggiorna manualmente dalle preferenze purtroppo.

**Comment by dentaku65** [comment]
Ops questa mi è proprio nuova; discutiamone nel forum pls
