### ISSUE TITLE
Problem con flash x

### ISSUE THREAD

**Issue by Albe46** [streamondemand/plugin.video.streamondemand#64]
Problema con flash x che riproduce il video di disabilitazione dell'adblock della durata di 46sec

**Comment by costaplus** [comment]
Potresti almeno specificare il canale e un'esempio esatto ?
Che piattaforma usi ?
Si più preciso. Grazie.

Costaplus

**Comment by Albe46** [comment]
Canale cineblog , video di "pubblicità " flashX, os openelec, opendns .L'ho provato su più film..

**Comment by dentaku65** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=22&t=8018&start=60

won't fix al momento
