### ISSUE TITLE
Problema CB01 con Serie TV

### ISSUE THREAD

**Issue by Andrjs** [streamondemand/plugin.video.streamondemand#65]
Ciao,
non so se il problema è solo mio, ma quando entro nei vari episodi di una serie tv in questo canale non mi da alcun link. Il sito mi sembra funzionante.
Grazie

**Comment by DjDiabolik** [comment]
Io da un paio di giorni sto notando che cineblog01 non compare + tra i miei canali addirittura e sono andato a vedere i suoi 2 file sono nella cartella channels.
Li ho ripresi da qua e ricopiati... gli ho dato attributi 777 ma niente... non compare.

**Comment by dentaku65** [comment]
fixed
