### ISSUE TITLE
canali non funzionani

### ISSUE THREAD

**Issue by JLDon** [streamondemand/plugin.video.streamondemand#66]
Complimenti, e ancora una volta come successo il mese scorso,aldilà delle migliorie che sostenete di aver apportato, canali come altadefinizioneclick hanno le library vuote e ogni collegamento é inesistente. Vi preghiamo di contattare i vari canali e collaborando con essi,risolvere ogni sorta di problema. SOD sarà pure un bel lavoro ma solo intellettualmente parlando per via dei bug,da principio, e inseguito per un discorso anche di funzionalitá per un addon del genere che dovrebbe essere migliore sotto ogni aspetto e per ultimo anche bello da vedere e da usare.Miglioriamo questi errori? Sono sicuro che,se vi applicaste, riuscireste a sviluppare un  addon completamente nuovo anche come interfaccia. 

P.S: Aggiungendo nuovamente l'addon,dopo aver pulito cache e file nella library inerenti all'addon, non si risolvono assolutamente i problemi riscontrati. Il sistema e gli addon sono  aggiornati,ma quei canali non funzionano,raggiungo bene i collegamenti con altri canali da superfavourites ma non quelli provenienti da altadefinizioneclick,lo scorso mese non funzionava 01, e menomale che credevo click esente da problemi. Il prossimo mese quale canale non sará raggiungibile?

nulla di personale e non aggiungo altro, riportare questi problemi,come utente e consumatore é un dovere

**Comment by phede86** [comment]
Stesso problema su cineblog01, ci sono solo trailer di YouTube.

**Comment by costaplus** [comment]
Caro JLdon,
è veramente complicato stare dietro a tutti i singoli siti che mettono a disposizione materiale che ovviamente sappiamo con quale finalità!
Il nostro lavoro in generale è portare avanti si SoD, ma nel tempo libero. Quindi apprezzando le tue impressioni su SoD ti chiedo di farne parte attivamente e metterti anche tu a perdere il tuo tempo gratuitamente per rendere SoD migliore per tutti.

Costaplus

**Comment by DjDiabolik** [comment]
Io ragazzi avevo già segnalato la cosa su un'altro issue chiuso, visto che ora sono le 3 di notte, ieri pomeriggio.
Cioè in teoria la cosa riguardava proprio cineblog01....... a me personalmente tale canale non compare + nella lista dei canali e ho appena notato che il file .xml che ho nella cartella "channels" (su osmc -> /home/osmc/.kodi/addons/plugin.video.streamondemand/channels/) è completamente vuoto.

Io vi suggerirei di andare su github... scaricare tutto il contenuto di tale cartella e quindi riversare tutti i canali e credo che almeno cosi siamo sicuri che abbiamo tutti i canali aggiornati e in linea con quelli sul server.......

**Comment by RaspberryPiZero** [comment]
@JLDon Purtroppo non è così semplice sistemare circa 60 canali ogni giorno. Ogni giorno ci sono nuovi bug, che verranno sistemati il prima possibile. È un add-on totalmente gratuito e penso che questo sia il massimo che loro possano fare.

Se non ti va un canale e vuoi usarlo subito, installati chromium e naviga con il browser sul canale. Ci sono modi più garbati per segnalare un bug (che tra l'altro è già noto).

**Comment by RaspberryPiZero** [comment]
@DjDiabolik Io non ho nessun .xml o .py di cb vuoto e considera che ho un'installazione di OSMC che non modifico da mesi. Se vedi discrepanze con la versione di github conviene disinstallare tutto, cancellare la cartella userdata>addondata>stream on demand e riavviare. Il fix per le fonti di cb arriverà, abbiate fede.

**Comment by dentaku65** [comment]
github issue serve per segnalare problemi inerenti al codice... è già stato detto che l'autoupdate non funziona, scaricatevi manualmente i canali e i server con i relativi xml

@JLDon impacchetta tutto e spedisci indietro il pacchetto che te lo ripariamo gratuitamente
@DjDiabolik come detto ne abbiamo parlato ampiamente sul forum
@RaspberryPiZero thx

**Comment by DjDiabolik** [comment]
Ma sul forum quale ? Mimediacenter ? Ma è seguito quel forum oppure c'è altro posto ?

**Comment by costaplus** [comment]
Ciao a tutti, 
avevo risposto, e poi ci ho ripensato per non aprire polemine inutili, ma voglio comunque dire la mia.

**@JLDon** oltre a contribuire con le lamentele di mal funzionamento, potresti sempre cimentarti e sistemare te le cose che non vanno, in modo da avere altri volontari disponibili che perdono il loro tempo per gli altri, in alternativa puoi attivarti un bel abbonamento a netflix così potrai lamentare i malfunzionamenti, forse lì ti daranno più ascolto.

**@DjDiabolik** Il forum mimediacenter è diciamo un punto ufficiale di ritrovo nella sezione **pelisalacarta (For Italian users)**. La tua domanda se è seguito quel forum ? la risposta è che a parte poche persone interessate in toto al progetto, spesso chi scrive è solo per risolvere il suo problema e poi sparisce senza nemmeno ringraziare, morale solo per convenienza.

@ Per tutti Ripeto il progetto va avanti grazie a veramente pochissime persone che si cimentano nel proprio tempo libero, ma se siete interessati potete anche partecipare allo sviluppo, non ci vuole poi tantissimo, ma un pàò di impegno anche solo a trovare bug è un lavoro.
Avewvo aperto una sezione dove spiegavo come fare [Qui](http://www.mimediacenter.info/foro/viewtopic.php?f=38&t=7913), ma come potete notare a parte alcuni nessuno si è poi più di tanto interessato.

**Comment by JLDon** [comment]
cosa  devo scaricare e come lo devo inserire in sreaming on demand  sul mio osmc

**Comment by RaspberryPiZero** [comment]
Sinceramente sono anche io stufo di personaggi come questi. Continuo a sostenere che SOD dovrebbe essere a pagamento mensile o semestrale (Bitcoin ovviamente) per una versione "Premium" con aggiornamenti prioritari.

**Comment by DjDiabolik** [comment]
@RaspberryPiZero caro mio.... se proprio vogliamo dirlo quello che fa già di per il SOD è di poco legale.... mettici pure che diventi a pagamento poi voglia a dire che l'addons non fornisce link suoi.
Te ne citerei di altri addons atti a farti vedere contenuti in streaming.... alcuni di questi col tempo sono diventati a pagamento e molti hanno fanno una finaccia tant'è che in rete circolano voci che anche i developers dello stesso kodi hanno richiasto di essere tirati dentro...... 

Sei stufo poi di tali personaggi ? Vorrei sapere qual'è il tuo contributo............. il mio è quasi pari a zero perchè mi sono limitato solo a riportare eventuali problemi sperando di fare cosa gradita ma se cosi non è la prossima volta evito.

Per rispondere a @costaplus 
Riguardo al forum......... ricordi no la cosa del sito che stavo provando ad aggiungere... dopo i primi reply in cui ti limitavi a scrivere che avevi già scritto tutto in post precedenti non è che eri poi di cosi grande aiuto poi per carità coglione io che non sono stato capace di capirlo.

Che ti/vi devo dire.......se un giorno il developing di questo addons si fermerà morto un papa se ne fa un'altro e se un'altro non ci sarà personalmente me ne farrò una ragione...

Buona giornata.

**Comment by RaspberryPiZero** [comment]
Ma cosa devono dire quelli di Kodi? Tentano di nascondersi dietro ad un fiammifero ma la realtà dei fatti è questa. Se non ci fossero add-on come Stream On Demand Kodi sarebbe già morto e sepolto (trovami le persone che lo usano solamente come media center per i propri file). Poi qui siamo comunque off-topic. Io intendevo una versione "Premium" dell'Add-on con fix che arrivano precedentemente rispetto alla versione classica, una sorta di "corsia preferenziale". Loro offrono il poco tempo libero che hanno. Il tempo non te lo rende nessuno, perché non premiarli? Io non vedo pubblicità su SOD, su Cineblog sì.

Prima di segnalare un problema, fai le solite procedure:

- Reinstallazione
- Cancellazione folder userdata
- Cambio DNS
- Aggiorna Kodi/OSMC/Libre all'ultima versione (evita le beta)
- Etc etc

Buona fortuna

**Comment by DjDiabolik** [comment]
@RaspberryPiZero non so a chi sia riferita sta cosa che tu chiami personaggi ma io metto le mani avanti:
Io quando ho segnalato problemi da queste parti è pensando di fare una cosa gradita...... sopratutto l'ho sempre fatto perchè vedevo che c'erano altri issue aperti però se appunto è preferibile usare il forum (che cmq conoscevo già) ne prenderò atto.
Figurati poi......... ci sono diversi altri canali e se uno non va mica si muore.

Ripeto solo che io ho notato sta cosa appunto che rispetto al file .xml qua su GitHUB io mi sono ritrovato il file .xml completamente bianco e magari ci sta che si sia corrotto o mal aggiornato oppure chi diavolo lo sa cos'è accaduto e mi sono solo limitato a dire che io notavo la scomparsa completa del canale..... tutto qua.

Cmq sia la mia attuale installazione del SOD è di mooooolti mesi fà.... ci sta pure che all'interno della mia cartella ci siano tracce di vecchie versioni. C'è una cosa che ho fatto di recente........ che in teoria dovrebbe equivalere a rifare l'installazione:
In pratica ho preso e scaricato lo zip-master da github poi ho cancellato tutte le sue cartelle dal mio Pi2 e quindi ho riestratto lo zip appena scaricato e in seguito reimpostato i CHMOD ai vari file su 775 cosi com'erano prima di cancellare le cartelle.
In teoria cosi facendo è come se si fa una disinstallazione è una reinstallazione pulita e questa l'ho fatta per la versione precedente dopo aver appreso appunto che l'autoupdate dei canali poteva aver qualche problema.

**Comment by DjDiabolik** [comment]
Poi voglio dire una cosa a @JLDon cioè dai..... almeno un pò di impegno e dedicarsi 5 minuti a fare una ricerca su google.
Ci sono almeno 10 blog italiani che trattano gli addons + o - legali del kodi.............. e tra questi 10 almeno in 6 trovi guide su come installare Stream on Demand.......... dai su...

**Comment by DjDiabolik** [comment]
@RaspberryPiZero sul discorso della legalità infatti è mooolto ampio....... pensa che io ho conosciuto questo addons almeno 3 mesi dopo l'acquisto del mio Pi2 e l'installazione stessa dell'OSMC.
E anche oggi a volte preferisco ancora appoggiarmi al caro e vecchio P2P anche perchè a volte il mondo dello streaming non è proprio in linea con quello che viene rilasciato nel P2P e a volte ciò che si trova nel P2P non lo ritrovi nei vari blog di streaming e viceversa... spero di essermi spiegato bene.
