### ISSUE TITLE
SerieHD e piccioni

### ISSUE THREAD

**Issue by axlt2002** [streamondemand/plugin.video.streamondemand#7]
Ciao,

Segnalo un problema di accesso a SerieHD tramite SOD; il sito è perfettamente raggiungibile via web.
Inoltre, sembra siano riapparsi i piccioni su Openload (provato tramite un altro sito).

Fatemi sapere se serve un log.

Buona giornata,

Alex

- Update

Volevo solo specificare che il problema di accesso a SerieHD si verfica per il branch merge_20160721; con la 5.3.2 tutto è ok.
Openload invece da errore per entrambe le versioni.

**Comment by dentaku65** [comment]
fixed with 5.3.3
