### ISSUE TITLE
ricerca globale

### ISSUE THREAD

**Issue by sgiannulli** [streamondemand/plugin.video.streamondemand#75]
ciao,
ho aggiornato alla 5.4.4 su kodi 16/windows 7 e la ricerca globale non funziona più: escono due cartelle (film e serie ?) con contenuti vuoti. Stranamente l'aggiornamento su macchina Debian è andato liscio.
Ho già provato a disinstallare e installare 2 volte (cancellando anche la cartella dei settings) ma niente: qualche suggerimento?
grazie

**Comment by matteopic** [comment]
Nel file di log è riportato qualche errore?

**Comment by sgiannulli** [comment]
ciao,
tutte le volte trovo questo:
`17:28:17 T:5244   ERROR: Unable to find plugin
17:28:17 T:3728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
17:28:17 T:3728   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
17:30:35 T:3356   ERROR: Unable to find plugin
17:30:35 T:3728   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
17:30:35 T:3728   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
`

**Comment by dentaku65** [comment]
prova a copiare buscador.py e .xml e buscadorall.py e .xml da github alla tua dir /channels

**Comment by sgiannulli** [comment]
purtroppo niente da fare.....adesso non vanno più neanche youtube trailer e preferiti.......e il tutto dopo aver disinstallato e installato da capo ancora
spero non sia qualcosa di corrotto in kodi

**Comment by dentaku65** [comment]
a me sembra che non hai installato correttamente l'addon o che in qualche modo Kodi sul tuo sistema ha dei problemi

**Comment by mrmister68** [comment]
ciao , 
ho riscontrato il seguente problema utilizzando SPMC, 
quando ci si trova sulla pagina di un server, e si preme back per tornare alla pagina precente, quella che elenca tutti i server trovati, riparte la ricerca dei server; su kodi il problema non si verifica

**Comment by sgiannulli** [comment]
alla fine ho risolto disinstallando e reinstallando kodi; evidentemente qualche file o il database corrotto.
per me si può chiudere
