### ISSUE TITLE
TheV(Punto)me Rick Rolld

### ISSUE THREAD

**Issue by RaspberryPiZero** [streamondemand/plugin.video.streamondemand#76]
Sulle fonti di TheV(Punto)me viene fuori il famoso video di Rick Astley con su scritto che "sono stati violati i termini etc".

**Comment by Bonobomagno** [comment]
theV?

**Comment by dentaku65** [comment]
Questo succede dal sito originario dove è linkato il video

**Comment by Dr-Zer0** [comment]
Sistemato da un po'
