### ISSUE TITLE
"back" esce dall'addon anziché tornare indietro di un livello

### ISSUE THREAD

**Issue by nonnopaolo** [streamondemand/plugin.video.streamondemand#84]
Nelle ultime versioni dell'addon per tornare indietro di livello si deve OBBLIGATORIAMENTE cliccare sui due puntini presenti in genere nella prima riga delle opzioni. 
Sia sotto windows (usando il tasto destro del mouse) che sotto android (usando i tasti back o return dei telecomandi) si esce del tutto dall'addon, anziché tornare indietro di un solo livello.
Sarebbe opportuno ripristinare il precedente funzionamento.
Grazie

**Comment by dentaku65** [comment]
C'e' qualcosa di configurato male nel tuo Kodi. Il back funziona correttamente

**Comment by nonnopaolo** [comment]
Avevo specificato che il problema sta accadendo in tutte le versioni che ho installato (win10 e android) ed a partire da una certa release. Ad ogni modo: in quale parte della configurazione dovrei controllare secondo te?
