### ISSUE TITLE
cineblog01

### ISSUE THREAD

**Issue by crashinside** [streamondemand/plugin.video.streamondemand#85]
Da qualche giorno tutti i link di cineblog01 risultano non funzionanti.

**Comment by Dr-Zer0** [comment]
Ciao,
abbiamo verificato che i link sono funzionanti.
Controlla la tua configurazione e connessione internet.

**Comment by crashinside** [comment]
Ho provato ora, la parte film funziona, la parte serie TV non funziona. Ogni volta che clicco su qualsiasi server tipo openload, ecc.. mi restituisce errore

**Comment by SandraGi** [comment]
La parte serie tv di cineblog01  restituisce immediatamente plugin errore di connessione al server
