### ISSUE TITLE
Cineblog problema serie TV 

### ISSUE THREAD

**Issue by crashinside** [streamondemand/plugin.video.streamondemand#86]
Ho provato ora, la parte film funziona, la parte serie TV non funziona. Qualsiasi serie TV scelga, quando clicco su qualsiasi server tipo openload, ecc.. mi restituisce errore

**Comment by Scruffy3000** [comment]
Prova a dare un'occhiata a https://github.com/streamondemand/plugin.video.streamondemand/pull/87

**Comment by crashinside** [comment]
perfetto! funziona!

**Comment by SandraGi** [comment]
Di nuovo stesso problema...
