### ISSUE TITLE
Ricerche ripetute

### ISSUE THREAD

**Issue by nonnopaolo** [streamondemand/plugin.video.streamondemand#88]
Ho riscontrato che quando si torna indietro dalla pagina di un server (quella ad esempio con le puntate di una serie), ripete sempre la ricerca dei server.
Esempio: ricerca globale -> cerco una serie/film -> ottengo la lista di serie/film che soddisfano i criteri di ricerca -> seleziono la serie/film -> (parte la ricerca dei server con pausa più o meno lunga, con il contatore della % di completamento in alto a destra nella schermata) -> ottengo la lista dei server -> seleziono un server -> ottengo la lista delle puntate. 
Se adesso torno indietro alla pagina con la lista di serie/film cercati, ripete un'altra volta la ricerca dei server, cosa che può rendere lenta e fastidiosa la ricerca di uno stream, nel caso che uno o più di uno non partano (cosa possibilissima, ovviamente).
C'è modo di ovviare a questa ripetizione della ricerca?
Grazie

**Comment by RaspberryPiZero** [comment]
Avevamo già affrontato più volte la questione all'interno del forum (forse è meglio se scrivi lì per segnalazioni di questo tipo). È un problema di Kodi 17.

**Comment by nonnopaolo** [comment]
Ok. Puoi darmi per favore il link del forum?
Grazie

**Comment by dentaku65** [comment]
SOD su Kodi 17 non è ancora stato rilasciato in via ufficiale
