### ISSUE TITLE
Condivisione remota biblioteca SOD 

### ISSUE THREAD

**Issue by thehutt61** [streamondemand/plugin.video.streamondemand#89]
Ciao
avendo più installazioni di KODI (OSMC, Windows, Android) con SOD sulla rete di casa e volendo mantenere allineate tutte le installazioni, avevo provato ad inserire l'indirizzo di una condivisione windows nel percorso dei files STRM nelle preferenze.
Poiché non funzionava ho provato a dare una sbirciatina al codice e ho trovato una paio di errori che ho corretto. 
Questo dovrebbe funzionare sia con la notazione _smb://SERVER/condivisione_ sia con _\\\SERVER\condivisione_
Se volete vi invio le correzioni in modo che possiate aggiungerle alla prossima release.

Durante le prove per risolvere il problema della condivisione remota mi sono imbattuto anche in un altro errore che si verifica aggiungendo una serie o un film per cui non è possibile individuare un unico titolo dall'interrogazione degli scraper.
In questo caso, infatti, dovrebbe essere visualizzata una finestra in cui si può scegliere il titolo corretto.
La finestra di scelta appare correttamente solo se si utilizza una risoluzione della skin di 720, mentre con una risoluzione di 1080 si riceve un messaggio di errore.
Il problema è dovuto alla mancanza, nelle cartelle "..\resources\skins\Default\" diverse da 720p del file "InfoWindow.xml".
La soluzione più rapida è quella di ricopiare il file nella/e directory in cui manca... la più pulita è quella di modificare il file in modo che si veda correttamente con la risoluzione utilizzata.

cordiali saluti

P.S. complimenti per l'ottimo Add-on

**Comment by dentaku65** [comment]
@thehutt61 grazie. Per l'invio di codici nuovi ti chiedo cortesemente di aspetare la prossima release che sarà già "abile" per Kodi 17... al momento abbiamo troppa carne al fuoco.

**Comment by thehutt61** [comment]
Non c'è problema...
Anzi ho dato un'occhiata veloce al branch e le chiamate alle funzioni incriminate sono fatte in maniera diversa e quindi il problema potrebbe non porsi più nella nuova versione.

**Comment by costaplus** [comment]
@thehutt61 ho corretto la mancanza dei file in 1080

**Comment by thehutt61** [comment]
@costaplus ottimo!

**Comment by thehutt61** [comment]
@dentaku65 nella versione 5.4.6 il problema segnalato è stato risolto...  
chiudo la segnalazione.

grazie di tutto
