### ISSUE TITLE
cb01

### ISSUE THREAD

**Issue by phede86** [streamondemand/plugin.video.streamondemand#90]
Con l'ultima versione 5.4.5 continua a non funzionare openload.

**Comment by dentaku65** [comment]
log?

**Comment by Scruffy3000** [comment]
Non è solo openload, https://github.com/streamondemand/plugin.video.streamondemand/commit/a7a86712cdfd3150d599012925d260a5c016cc49 .

Il mio fix era sicuramente orrendo (e probabilmente rompeva qualche caso limite), ma questo non funziona, senza stare a discutere del fare una richiesta quando basta estrarre un base64 da un'url.

**Comment by phede86** [comment]
Adesso sto provando con kodi 17 stabile ed é ritornato a funzionare normalmente.

**Comment by dentaku65** [comment]
@Scruffy3000 mi pare che il doc l'abbia sistemato a valle

**Comment by phede86** [comment]
Ok grazie mille
