### ISSUE TITLE
Info streamondemand

### ISSUE THREAD

**Issue by fra71195** [streamondemand/plugin.video.streamondemand#91]
Salve,
è possibile aggiungere delle informazioni riguardo ai film all'interno del plugin?
Penso sarebbe una cosa utile, qualcuno può consigliarmi qualcosa?
Grazie

**Comment by dentaku65** [comment]
Ci sono già

**Comment by fra71195** [comment]
potresti darmi indicazioni su come trovarli dato che non li vedo?
