### ISSUE TITLE
Aggiungere video in 4k

### ISSUE THREAD

**Issue by phede86** [streamondemand/plugin.video.streamondemand#95]
Salve, volevo sapere se era possibile aggiungere il formato 4k dato che è disponibile su molti siti, grazie.

**Comment by costaplus** [comment]
Ciao,
se puoi essere un pò più preciso di dove siao questi 4k ? 
Se me li indichi faccio un canale nell'immediato!!

**Comment by costaplus** [comment]
Sto ancora aspettando il tuo spunto !!!

**Comment by phede86** [comment]
Cb01 carica video in 4k anche se non sono accessibili dall' add-on.

**Comment by costaplus** [comment]
li trovi sicuramente nella ricerca, ma a parte la dicitura se vai nel dettaglio sono i soliti rip... 
ho provato comuque ad aggiungere al menù i 4k, ma ti assicuro nulla di qualitativamente avanzato rispetto al solito cb01!
Mi spiace...

Se hai altri link utili ... possiamo comunque provarci.

**Comment by phede86** [comment]
Io solo quello conoscevo e wuaki.tv però se sono compressi é inutile aggiungerli.
